"use client";

import { useCallback, useEffect, useRef, useState, type ReactNode } from "react";
import { RefreshCw } from "lucide-react";
import { ACA_OVERVIEW_THRESHOLD_DAYS, type AcaOverviewPerson, type AcaOverviewSnapshot, type AcaOverviewThresholdDays } from "@/lib/enrollment/aca-overview-types";
import { applyResponsibleAssignment } from "@/lib/enrollment/aca-overview-assign";
import { AcaAssignPicker } from "./AcaAssignPicker";

type Props = { from: string; to: string; onOpenRecord: (id: string) => void };

export function AcaOverviewDashboard({ from, to, onOpenRecord }: Props) {
  const [snapshot, setSnapshot] = useState<AcaOverviewSnapshot | null>(null);
  const [matrixMode, setMatrixMode] = useState<"occupancy" | "speed">("occupancy");
  const [threshold, setThreshold] = useState<AcaOverviewThresholdDays>(3);
  const [editingQueue, setEditingQueue] = useState(false);
  const [updatingQueueEmail, setUpdatingQueueEmail] = useState<string | null>(null);
  const [queueError, setQueueError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const sequence = useRef(0);
  const load = useCallback(async () => {
    const current = ++sequence.current; setLoading(true); setError(null);
    try {
      const params = new URLSearchParams({ thresholdDays: String(threshold) });
      if (from) params.set("from", from); if (to) params.set("to", to);
      const response = await fetch(`/api/enrollment/aca-overview?${params}`, { cache: "no-store" });
      const payload = await response.json().catch(() => null) as AcaOverviewSnapshot | { error?: string } | null;
      if (!response.ok) throw new Error(payload && "error" in payload ? payload.error : "Could not load ACA overview.");
      if (current === sequence.current) setSnapshot(payload as AcaOverviewSnapshot);
    } catch (cause) { if (current === sequence.current) setError(cause instanceof Error ? cause.message : "Could not load ACA overview."); }
    finally { if (current === sequence.current) setLoading(false); }
  }, [from, threshold, to]);
  useEffect(() => { void load(); return () => { sequence.current += 1; }; }, [load]);
  if (loading && !snapshot) return <Message>Loading ACA operations...</Message>;
  if (error && !snapshot) return <Message error={error} onRetry={() => void load()} />;
  if (!snapshot) return <Message>No ACA overview data.</Message>;
  const period = snapshot.period.from && snapshot.period.to ? `${snapshot.period.from} – ${snapshot.period.to}` : "All dates";
  const handleAssigned = (recordId: string, email: string | null, updatedAt?: string) => setSnapshot((current) => current ? { ...current, actions: applyResponsibleAssignment(current.actions, recordId, email), unassigned: current.unassigned.filter((row) => row.recordId !== recordId), people: current.people.map((row) => row.email === email ? { ...row, holding: row.holding + 1 } : row) } : current);
  const handleToggleQueue = useCallback(async (email: string, enabled: boolean) => {
    setUpdatingQueueEmail(email); setQueueError(null);
    try {
      const response = await fetch("/api/enrollment/aca-overview/queue-members", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, enabled }) });
      const payload = await response.json().catch(() => null) as { error?: string } | null;
      if (!response.ok) throw new Error(payload?.error ?? "Could not update the assignment queue.");
      await load();
    } catch (cause) {
      setQueueError(cause instanceof Error ? cause.message : "Could not update the assignment queue.");
    } finally { setUpdatingQueueEmail(null); }
  }, [load]);
  return <div className="space-y-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold text-[#6b778c]">Created-date cohort · {period}</p><p className="mt-1 text-xs text-[#8993a4]">Dashboard snapshot {new Date(snapshot.generatedAt).toLocaleString()}</p></div><div className="flex items-center gap-2"><label className="text-xs font-bold text-[#6b778c]">Stuck/silent ≥ <select value={threshold} onChange={(e) => setThreshold(Number(e.target.value) as AcaOverviewThresholdDays)} className="rounded border border-[#cfd8e5] bg-white px-2 py-1.5 text-xs font-bold text-[#344054]">{ACA_OVERVIEW_THRESHOLD_DAYS.map((value) => <option key={value} value={value}>{value} days</option>)}</select></label><button type="button" onClick={() => void load()} className="inline-flex items-center gap-1.5 rounded border border-[#cfd8e5] bg-white px-3 py-2 text-xs font-bold text-[#344054]"><RefreshCw className="h-3.5 w-3.5" />Refresh</button></div></div>
    <AcaScorecards scorecards={snapshot.scorecards} thresholdDays={snapshot.thresholdDays} />
    <section className="overflow-hidden rounded-lg border border-[#e6eaf0] bg-white"><Header title="Pipeline by stage" caption="Terminal stages are excluded from live waiting percentages."/><div className="overflow-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-[#fafbfc] text-left text-[11px] font-bold uppercase tracking-wide text-[#6b778c]"><tr><th className="px-4 py-3">Stage</th><th className="px-4 py-3 text-right">In stage</th><th className="px-4 py-3 text-right">Share</th><th className="px-4 py-3 text-right">Median wait</th><th className="px-4 py-3 text-right">Longest</th><th className="px-4 py-3 text-right">Stuck</th><th className="px-4 py-3 text-right">Silent</th></tr></thead><tbody>{snapshot.stageTable.map((row) => <tr key={row.stageId ?? "unassigned"} className="border-t border-[#ebecf0]"><td className="px-4 py-3 font-semibold text-[#42526e]"><span className="mr-2 inline-block h-2.5 w-2.5 rounded-sm" style={{ backgroundColor: row.stageColor ?? "#c1c7d0" }}/>{row.stageLabel}</td><td className="px-4 py-3 text-right font-bold">{row.inStage}</td><td className="px-4 py-3 text-right">{row.sharePercent == null ? "—" : `${row.sharePercent.toFixed(1)}%`}</td><td className="px-4 py-3 text-right">{formatDays(row.medianWaitDays)}</td><td className="px-4 py-3 text-right">{formatDays(row.longestWaitDays)}</td><td className="px-4 py-3 text-right">{row.stuckCount ?? "—"}</td><td className="px-4 py-3 text-right">{row.silentCount ?? "—"}</td></tr>)}</tbody></table></div></section>
    <div className="grid gap-4 xl:grid-cols-2"><ActionSection title="Needs action" rows={snapshot.actions} onOpenRecord={onOpenRecord} people={snapshot.people.filter((person) => person.email).map((person) => ({ email: person.email!, name: person.name, canWork: true, queueEnabled: true }))} onAssigned={handleAssigned}/><ActionSection title="Unassigned" rows={snapshot.unassigned} onOpenRecord={onOpenRecord} people={snapshot.people.filter((person) => person.email).map((person) => ({ email: person.email!, name: person.name, canWork: true, queueEnabled: true }))} onAssigned={handleAssigned} assignable/></div>
    <section className="overflow-hidden rounded-lg border border-[#e6eaf0] bg-white"><Header title="People" caption="Open assigned work in the selected created-date cohort."/><div className="overflow-auto"><table className="w-full min-w-[720px] text-sm"><thead className="bg-[#fafbfc] text-left text-[11px] font-bold uppercase tracking-wide text-[#6b778c]"><tr><th className="px-4 py-3">Person</th><th className="px-4 py-3 text-right">Holding</th><th className="px-4 py-3 text-right">Stuck</th><th className="px-4 py-3 text-right">Silent</th><th className="px-4 py-3 text-right">Median wait</th><th className="px-4 py-3 text-right">Done</th></tr></thead><tbody>{snapshot.people.map((row) => <tr key={row.email ?? "unassigned"} className="border-t border-[#ebecf0]"><td className="px-4 py-3 font-semibold text-[#42526e]">{row.name ?? row.email ?? "Unassigned"}</td><td className="px-4 py-3 text-right font-bold">{row.holding}</td><td className="px-4 py-3 text-right">{row.stuck}</td><td className="px-4 py-3 text-right">{row.silent}</td><td className="px-4 py-3 text-right">{formatDays(row.medianWaitDays)}</td><td className="px-4 py-3 text-right">{row.doneInPeriod}</td></tr>)}</tbody></table></div></section>
    <section className="overflow-hidden rounded-lg border border-[#e6eaf0] bg-white"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-[#ebecf0] px-4 py-3"><div><h2 className="text-sm font-bold text-[#172b4d]">Person × stage</h2><p className="mt-0.5 text-xs text-[#6b778c]">{matrixMode === "occupancy" ? "Current open occupancy and stuck counts." : "Historical median completed dwell; fewer than 10 attributed samples shows —."}</p></div><div className="inline-flex rounded border border-[#cfd8e5] p-0.5 text-xs font-bold"><button type="button" onClick={() => setMatrixMode("occupancy")} className={`rounded px-2 py-1 ${matrixMode === "occupancy" ? "bg-[#e9f2ff] text-[#0c66e4]" : "text-[#6b778c]"}`}>Occupancy</button><button type="button" onClick={() => setMatrixMode("speed")} className={`rounded px-2 py-1 ${matrixMode === "speed" ? "bg-[#e9f2ff] text-[#0c66e4]" : "text-[#6b778c]"}`}>Speed</button></div></div><div className="overflow-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-[#fafbfc] text-left text-[11px] font-bold uppercase tracking-wide text-[#6b778c]"><tr><th className="sticky left-0 z-10 bg-[#fafbfc] px-4 py-3">Person</th>{snapshot.matrix.stageLabels.map((label) => <th key={label} className="px-4 py-3 text-right">{label}</th>)}</tr></thead><tbody>{snapshot.matrix.rows.map((row) => <tr key={row.email ?? "unassigned"} className="border-t border-[#ebecf0]"><td className="sticky left-0 z-10 bg-white px-4 py-3 font-semibold text-[#42526e]">{row.name ?? "Unassigned"}</td>{row.cells.map((cell, index) => <td key={snapshot.matrix.stageIds[index]} className="px-4 py-3 text-right">{matrixMode === "occupancy" ? <><span className="font-bold">{cell.tasks}</span><span className="ml-1 text-xs text-[#8993a4]">({cell.stuck} stuck)</span></> : row.email ? <span className="font-bold text-[#42526e]">{snapshot.personStageTiming.cells[row.email]?.[snapshot.matrix.stageIds[index]]?.medianDays == null ? "—" : `${snapshot.personStageTiming.cells[row.email][snapshot.matrix.stageIds[index]].medianDays}d`}</span> : "—"}</td>)}</tr>)}</tbody></table></div></section>
    <section className="overflow-hidden rounded-lg border border-[#e6eaf0] bg-white"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-[#ebecf0] px-4 py-3"><div><h2 className="text-sm font-bold text-[#172b4d]">Assignment queue</h2><p className="mt-0.5 text-xs text-[#6b778c]">Never assigned first, then oldest assignment. Holding/stuck are informational. · {period}</p></div><button type="button" onClick={() => { setEditingQueue((value) => !value); setQueueError(null); }} className="rounded border border-[#cfd8e5] bg-white px-3 py-1.5 text-xs font-bold text-[#344054]">{editingQueue ? "Done" : "Edit queue"}</button></div>{editingQueue ? <div className="border-b border-[#ebecf0] bg-[#fbfdff] px-4 py-3">{queueError ? <p className="mb-2 rounded border border-[#ffbdad] bg-[#ffebe6] px-3 py-2 text-xs font-semibold text-[#bf2600]">{queueError}</p> : null}<div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{snapshot.people.filter((person) => person.email).map((person) => { const email = person.email!; const enabled = snapshot.queue.some((card) => card.email === email); return <label key={email} className={`flex items-center justify-between gap-3 rounded border px-3 py-2 text-sm font-semibold ${enabled ? "border-[#b3d4ff] bg-white text-[#172b4d]" : "border-[#dfe3ea] bg-[#f4f5f7] text-[#667085]"}`}><span className="min-w-0 truncate">{person.name ?? email}</span><input type="checkbox" checked={enabled} disabled={updatingQueueEmail === email} onChange={(event) => void handleToggleQueue(email, event.target.checked)} className="h-4 w-4 shrink-0 rounded border-[#c1c7d0] disabled:opacity-50" /></label>; })}</div></div> : null}<div className="flex gap-3 overflow-x-auto p-4 pb-5">{snapshot.queue.map((person) => <div key={person.email} className="min-w-[180px] rounded-lg border border-[#dfe1e6] bg-[#fafbfc] p-3"><p className="font-bold text-[#172b4d]">{person.name ?? person.email}</p><p className="mt-2 text-xs text-[#6b778c]">Holding <b>{person.holding}</b> · Stuck <b>{person.stuck}</b></p><p className="mt-1 text-[11px] text-[#8993a4]">{person.lastAssignedAt ? `Last assigned ${new Date(person.lastAssignedAt).toLocaleDateString()}` : "Never assigned"}</p></div>)}{snapshot.queue.length === 0 ? <p className="text-sm text-[#8993a4]">Nobody is enabled in the queue.</p> : null}</div></section>
  </div>;
}
function Header({ title, caption }: { title: string; caption: string }) { return <div className="border-b border-[#ebecf0] px-4 py-3"><h2 className="text-sm font-bold text-[#172b4d]">{title}</h2><p className="mt-0.5 text-xs text-[#6b778c]">{caption}</p></div>; }
function AcaScorecards({ scorecards, thresholdDays }: { scorecards: AcaOverviewSnapshot["scorecards"]; thresholdDays: number }) {
  const tile = (label: string, value: string | number, tone = "text-[#172b4d]", detail?: string) => <div className="rounded border border-[#ebecf0] bg-[#fafbfc] px-3 py-2.5"><p className="text-[10px] font-bold uppercase tracking-wide text-[#8993a4]">{label}</p><p className={`mt-1 text-2xl font-bold ${tone}`}>{value}</p>{detail ? <p className="mt-0.5 text-[11px] font-medium text-[#6b778c]">{detail}</p> : null}</div>;
  const days = (value: number | null) => value == null ? "—" : `${Number.isInteger(value) ? value : value.toFixed(1)}d`;
  const measuredDays = (value: number | null) => value == null ? "Not enough samples" : days(value);
  const tone = (value: number) => value ? "text-[#bf2600]" : "text-[#00875a]";
  return <div className="space-y-3">
    <ScorecardGroup title="Volume">{tile("Total tasks", scorecards.totalTasks)}{tile("Open", scorecards.open)}{tile("Done", scorecards.done, "text-[#00875a]")}{tile("Terminated", scorecards.terminated, "text-[#bf2600]")}{tile("Unassigned", scorecards.unassigned, tone(scorecards.unassigned))}</ScorecardGroup>
    <ScorecardGroup title="Attention">{tile(`No activity ≥${thresholdDays}d`, scorecards.noActivity, tone(scorecards.noActivity))}{tile(`Stuck in stage ≥${thresholdDays}d`, scorecards.stuckInStage, tone(scorecards.stuckInStage))}{tile("Can't Contact", scorecards.cantContact)}{tile("Can not get ID card", scorecards.cannotGetIdCard)}{tile("Median open age", days(scorecards.medianOpenAgeDays))}</ScorecardGroup>
    <ScorecardGroup title="Speed and staffing">{tile("Median time to done", measuredDays(scorecards.medianTimeToDoneDays))}{tile("Slowest stage", scorecards.slowestStage ? days(scorecards.slowestStage.medianDays) : "Not enough samples", "text-[#172b4d]", scorecards.slowestStage?.stageLabel)}{tile("Median time in stage", days(scorecards.medianTimeInCurrentStageDays))}{tile("Active people", scorecards.activePeople)}{tile("Avg tasks per person", scorecards.avgTasksPerPerson == null ? "—" : scorecards.avgTasksPerPerson.toFixed(1))}</ScorecardGroup>
  </div>;
}
function ScorecardGroup({ title, children }: { title: string; children: ReactNode }) { return <section className="rounded-lg border border-[#e6eaf0] bg-white p-3"><h2 className="mb-2 px-1 text-[11px] font-bold uppercase tracking-wide text-[#6b778c]">{title}</h2><div className="grid grid-cols-2 gap-2 sm:grid-cols-3 xl:grid-cols-5">{children}</div></section>; }
function ActionSection({ title, rows, onOpenRecord, people, onAssigned, assignable = false }: { title: string; rows: AcaOverviewSnapshot["actions"]; onOpenRecord: (id: string) => void; people: readonly AcaOverviewPerson[]; onAssigned: (recordId: string, email: string | null, updatedAt?: string) => void; assignable?: boolean }) {
  const pageSize = 20;
  const [page, setPage] = useState(0);
  const pageCount = Math.max(1, Math.ceil(rows.length / pageSize));
  useEffect(() => { setPage((current) => Math.min(current, pageCount - 1)); }, [pageCount]);
  const visible = rows.slice(page * pageSize, (page + 1) * pageSize);
  return <section className="overflow-hidden rounded-lg border border-[#e6eaf0] bg-white"><Header title={title} caption="Sorted by the larger of stage age and silence."/><div className="divide-y divide-[#ebecf0]">{visible.map((row) => <div key={row.recordId} className="flex items-center justify-between gap-3 px-4 py-3 hover:bg-[#f8fafc]"><button type="button" onClick={() => onOpenRecord(row.recordId)} className="min-w-0 truncate text-left font-semibold text-[#42526e]">{row.clientName ?? row.taskId ?? row.recordId}</button><div className="flex shrink-0 items-center gap-2">{assignable ? <AcaAssignPicker recordId={row.recordId} expectedUpdatedAt={row.updatedAt} people={people} currentEmail={row.responsibleEmail} onAssigned={(email, updatedAt) => onAssigned(row.recordId, email, updatedAt)}/> : null}<span className="text-xs font-bold text-[#bf2600]">{row.sortDays}d {row.stageAgeEstimated ? "· est." : ""}</span></div></div>)}{rows.length === 0 ? <p className="px-4 py-6 text-sm text-[#8993a4]">Nothing currently matches.</p> : null}</div>{pageCount > 1 ? <div className="flex items-center justify-between border-t border-[#ebecf0] px-4 py-2 text-xs font-semibold text-[#6b778c]"><span>Page {page + 1} of {pageCount}</span><div className="flex gap-2"><button type="button" disabled={page === 0} onClick={() => setPage((current) => current - 1)} className="rounded border border-[#cfd8e5] px-2 py-1 disabled:opacity-40">Previous</button><button type="button" disabled={page === pageCount - 1} onClick={() => setPage((current) => current + 1)} className="rounded border border-[#cfd8e5] px-2 py-1 disabled:opacity-40">Next</button></div></div> : null}</section>;
}
function Message({ children, error, onRetry }: { children?: ReactNode; error?: string; onRetry?: () => void }) { return <div className={`rounded-lg border px-4 py-5 text-sm font-semibold ${error ? "border-[#ffbdad] bg-[#ffebe6] text-[#bf2600]" : "border-[#e6eaf0] bg-white text-[#6b778c]"}`}>{error ?? children}{onRetry ? <button type="button" onClick={onRetry} className="ml-3 rounded border border-current px-2 py-1 text-xs">Retry</button> : null}</div>; }
function formatDays(value: number | null) { return value == null ? "—" : `${Number.isInteger(value) ? value : value.toFixed(1)}d`; }
