"use client";

import { useCallback, useEffect, useRef, useState, type ReactNode } from "react";
import { RefreshCw } from "lucide-react";
import { ACA_OVERVIEW_THRESHOLD_DAYS, type AcaOverviewPerson, type AcaOverviewSnapshot, type AcaOverviewThresholdDays } from "@/lib/enrollment/aca-overview-types";
import { applyResponsibleAssignment } from "@/lib/enrollment/aca-overview-assign";
import { AcaAssignPicker } from "./AcaAssignPicker";

type Props = { from: string; to: string; onOpenRecord: (id: string) => void };

export function AcaOverviewDashboard({ from, to, onOpenRecord }: Props) {
  const [snapshot, setSnapshot] = useState<AcaOverviewSnapshot | null>(null);
  const [threshold, setThreshold] = useState<AcaOverviewThresholdDays>(3);
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const sequence = useRef(0);
  const load = useCallback(async () => {
    const current = ++sequence.current; setLoading(true); setError(null);
    try {
      const params = new URLSearchParams({ thresholdDays: String(threshold) });
      if (from) params.set("from", from); if (to) params.set("to", to);
      const response = await fetch(`/api/enrollment/aca-overview?${params}`, { cache: "no-store" });
      const payload = await response.json().catch(() => null) as AcaOverviewSnapshot | { error?: string } | null;
      if (!response.ok) throw new Error(payload && "error" in payload ? payload.error : "Could not load ACA overview.");
      if (current === sequence.current) setSnapshot(payload as AcaOverviewSnapshot);
    } catch (cause) { if (current === sequence.current) setError(cause instanceof Error ? cause.message : "Could not load ACA overview."); }
    finally { if (current === sequence.current) setLoading(false); }
  }, [from, threshold, to]);
  useEffect(() => { void load(); return () => { sequence.current += 1; }; }, [load]);
  if (loading && !snapshot) return <Message>Loading ACA operations...</Message>;
  if (error && !snapshot) return <Message error={error} onRetry={() => void load()} />;
  if (!snapshot) return <Message>No ACA overview data.</Message>;
  const period = snapshot.period.from && snapshot.period.to ? `${snapshot.period.from} – ${snapshot.period.to}` : "All dates";
  const handleAssigned = (recordId: string, email: string | null, updatedAt?: string) => setSnapshot((current) => current ? { ...current, actions: applyResponsibleAssignment(current.actions, recordId, email), unassigned: current.unassigned.filter((row) => row.recordId !== recordId), people: current.people.map((row) => row.email === email ? { ...row, holding: row.holding + 1 } : row) } : current);
  const card = (label: string, value: number | string, tone = "text-[#172b4d]") => <div className="rounded-lg border border-[#e6eaf0] bg-white px-4 py-3"><p className="text-[11px] font-bold uppercase tracking-wide text-[#6b778c]">{label}</p><p className={`mt-1 text-2xl font-bold ${tone}`}>{value}</p></div>;
  return <div className="space-y-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold text-[#6b778c]">Created-date cohort · {period}</p><p className="mt-1 text-xs text-[#8993a4]">Dashboard snapshot {new Date(snapshot.generatedAt).toLocaleString()}</p></div><div className="flex items-center gap-2"><label className="text-xs font-bold text-[#6b778c]">Stuck/silent ≥ <select value={threshold} onChange={(e) => setThreshold(Number(e.target.value) as AcaOverviewThresholdDays)} className="rounded border border-[#cfd8e5] bg-white px-2 py-1.5 text-xs font-bold text-[#344054]">{ACA_OVERVIEW_THRESHOLD_DAYS.map((value) => <option key={value} value={value}>{value} days</option>)}</select></label><button type="button" onClick={() => void load()} className="inline-flex items-center gap-1.5 rounded border border-[#cfd8e5] bg-white px-3 py-2 text-xs font-bold text-[#344054]"><RefreshCw className="h-3.5 w-3.5" />Refresh</button></div></div>
    <div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-5">{card("Total", snapshot.scorecards.totalTasks)}{card("Open", snapshot.scorecards.open)}{card("Done", snapshot.scorecards.done, "text-[#00875a]")}{card("Unassigned", snapshot.scorecards.unassigned, snapshot.scorecards.unassigned ? "text-[#bf2600]" : "text-[#00875a]")}{card("Stuck / silent", `${snapshot.scorecards.stuckInStage} / ${snapshot.scorecards.noActivity}`, snapshot.scorecards.stuckInStage || snapshot.scorecards.noActivity ? "text-[#bf2600]" : "text-[#00875a]")}</div>
    <section className="overflow-hidden rounded-lg border border-[#e6eaf0] bg-white"><Header title="Pipeline by stage" caption="Terminal stages are excluded from live waiting percentages."/><div className="overflow-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-[#fafbfc] text-left text-[11px] font-bold uppercase tracking-wide text-[#6b778c]"><tr><th className="px-4 py-3">Stage</th><th className="px-4 py-3 text-right">In stage</th><th className="px-4 py-3 text-right">Share</th><th className="px-4 py-3 text-right">Median wait</th><th className="px-4 py-3 text-right">Longest</th><th className="px-4 py-3 text-right">Stuck</th><th className="px-4 py-3 text-right">Silent</th></tr></thead><tbody>{snapshot.stageTable.map((row) => <tr key={row.stageId ?? "unassigned"} className="border-t border-[#ebecf0]"><td className="px-4 py-3 font-semibold text-[#42526e]"><span className="mr-2 inline-block h-2.5 w-2.5 rounded-sm" style={{ backgroundColor: row.stageColor ?? "#c1c7d0" }}/>{row.stageLabel}</td><td className="px-4 py-3 text-right font-bold">{row.inStage}</td><td className="px-4 py-3 text-right">{row.sharePercent == null ? "—" : `${row.sharePercent.toFixed(1)}%`}</td><td className="px-4 py-3 text-right">{formatDays(row.medianWaitDays)}</td><td className="px-4 py-3 text-right">{formatDays(row.longestWaitDays)}</td><td className="px-4 py-3 text-right">{row.stuckCount ?? "—"}</td><td className="px-4 py-3 text-right">{row.silentCount ?? "—"}</td></tr>)}</tbody></table></div></section>
    <div className="grid gap-4 xl:grid-cols-2"><ActionSection title="Needs action" rows={snapshot.actions} onOpenRecord={onOpenRecord} people={snapshot.people.filter((person) => person.email).map((person) => ({ email: person.email!, name: person.name, canWork: true, queueEnabled: true }))} onAssigned={handleAssigned}/><ActionSection title="Unassigned" rows={snapshot.unassigned} onOpenRecord={onOpenRecord} people={snapshot.people.filter((person) => person.email).map((person) => ({ email: person.email!, name: person.name, canWork: true, queueEnabled: true }))} onAssigned={handleAssigned} assignable/></div>
    <section className="overflow-hidden rounded-lg border border-[#e6eaf0] bg-white"><Header title="People" caption="Open assigned work in the selected created-date cohort."/><div className="overflow-auto"><table className="w-full min-w-[720px] text-sm"><thead className="bg-[#fafbfc] text-left text-[11px] font-bold uppercase tracking-wide text-[#6b778c]"><tr><th className="px-4 py-3">Person</th><th className="px-4 py-3 text-right">Holding</th><th className="px-4 py-3 text-right">Stuck</th><th className="px-4 py-3 text-right">Silent</th><th className="px-4 py-3 text-right">Median wait</th><th className="px-4 py-3 text-right">Done</th></tr></thead><tbody>{snapshot.people.map((row) => <tr key={row.email ?? "unassigned"} className="border-t border-[#ebecf0]"><td className="px-4 py-3 font-semibold text-[#42526e]">{row.name ?? row.email ?? "Unassigned"}</td><td className="px-4 py-3 text-right font-bold">{row.holding}</td><td className="px-4 py-3 text-right">{row.stuck}</td><td className="px-4 py-3 text-right">{row.silent}</td><td className="px-4 py-3 text-right">{formatDays(row.medianWaitDays)}</td><td className="px-4 py-3 text-right">{row.doneInPeriod}</td></tr>)}</tbody></table></div></section>
    <section className="overflow-hidden rounded-lg border border-[#e6eaf0] bg-white"><Header title="Person × stage" caption="Counts are open records; use the queue below for assignment order."/><div className="overflow-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-[#fafbfc] text-left text-[11px] font-bold uppercase tracking-wide text-[#6b778c]"><tr><th className="px-4 py-3">Person</th>{snapshot.matrix.stageLabels.map((label) => <th key={label} className="px-4 py-3 text-right">{label}</th>)}</tr></thead><tbody>{snapshot.matrix.rows.map((row) => <tr key={row.email ?? "unassigned"} className="border-t border-[#ebecf0]"><td className="px-4 py-3 font-semibold text-[#42526e]">{row.name ?? "Unassigned"}</td>{row.cells.map((cell, index) => <td key={snapshot.matrix.stageIds[index]} className="px-4 py-3 text-right"><span className="font-bold">{cell.tasks}</span><span className="ml-1 text-xs text-[#8993a4]">({cell.stuck} stuck)</span></td>)}</tr>)}</tbody></table></div></section>
    <section className="rounded-lg border border-[#e6eaf0] bg-white p-4"><Header title="Assignment queue" caption="Never assigned first, then oldest assignment. Holding/stuck are informational."/><div className="mt-3 flex gap-3 overflow-x-auto pb-1">{snapshot.queue.map((person) => <div key={person.email} className="min-w-[180px] rounded-lg border border-[#dfe1e6] bg-[#fafbfc] p-3"><p className="font-bold text-[#172b4d]">{person.name ?? person.email}</p><p className="mt-2 text-xs text-[#6b778c]">Holding <b>{person.holding}</b> · Stuck <b>{person.stuck}</b></p><p className="mt-1 text-[11px] text-[#8993a4]">{person.lastAssignedAt ? `Last assigned ${new Date(person.lastAssignedAt).toLocaleDateString()}` : "Never assigned"}</p></div>)}</div></section>
  </div>;
}
function Header({ title, caption }: { title: string; caption: string }) { return <div className="border-b border-[#ebecf0] px-4 py-3"><h2 className="text-sm font-bold text-[#172b4d]">{title}</h2><p className="mt-0.5 text-xs text-[#6b778c]">{caption}</p></div>; }
function ActionSection({ title, rows, onOpenRecord, people, onAssigned, assignable = false }: { title: string; rows: AcaOverviewSnapshot["actions"]; onOpenRecord: (id: string) => void; people: readonly AcaOverviewPerson[]; onAssigned: (recordId: string, email: string | null, updatedAt?: string) => void; assignable?: boolean }) { return <section className="overflow-hidden rounded-lg border border-[#e6eaf0] bg-white"><Header title={title} caption="Sorted by the larger of stage age and silence."/><div className="divide-y divide-[#ebecf0]">{rows.slice(0, 20).map((row) => <div key={row.recordId} className="flex items-center justify-between gap-3 px-4 py-3 hover:bg-[#f8fafc]"><button type="button" onClick={() => onOpenRecord(row.recordId)} className="min-w-0 truncate text-left font-semibold text-[#42526e]">{row.clientName ?? row.taskId ?? row.recordId}</button><div className="flex shrink-0 items-center gap-2">{assignable ? <AcaAssignPicker recordId={row.recordId} expectedUpdatedAt={row.updatedAt} people={people} currentEmail={row.responsibleEmail} onAssigned={(email, updatedAt) => onAssigned(row.recordId, email, updatedAt)}/> : null}<span className="text-xs font-bold text-[#bf2600]">{row.sortDays}d {row.stageAgeEstimated ? "· est." : ""}</span></div></div>)}{rows.length === 0 ? <p className="px-4 py-6 text-sm text-[#8993a4]">Nothing currently matches.</p> : null}</div></section>; }
function Message({ children, error, onRetry }: { children?: ReactNode; error?: string; onRetry?: () => void }) { return <div className={`rounded-lg border px-4 py-5 text-sm font-semibold ${error ? "border-[#ffbdad] bg-[#ffebe6] text-[#bf2600]" : "border-[#e6eaf0] bg-white text-[#6b778c]"}`}>{error ?? children}{onRetry ? <button type="button" onClick={onRetry} className="ml-3 rounded border border-current px-2 py-1 text-xs">Retry</button> : null}</div>; }
function formatDays(value: number | null) { return value == null ? "—" : `${Number.isInteger(value) ? value : value.toFixed(1)}d`; }
