import { describe, expect, it } from "vitest";
import {
  canEditColumnField,
  isAutoGeneratedColumn,
  nextPosition,
  slugifyColumnKey,
  sortColumns,
} from "./columns";
import type { TableColumn } from "./types";

const col = (key: string, position: number, label = key): TableColumn => ({
  id: key,
  scope: "aca",
  key,
  label,
  type: "text",
  is_system: false,
  position,
  pinned: false,
  hidden_default: false,
  show_in_detail: false,
  required: false,
  archived_at: null,
});

describe("slugifyColumnKey", () => {
  it("builds stable snake-case keys", () => {
    expect(slugifyColumnKey("FUB Link 2026!")).toBe("fub_link_2026");
    expect(slugifyColumnKey("   ")).toBe("custom_column");
  });
});

describe("sortColumns", () => {
  it("sorts by position then label then key", () => {
    expect(sortColumns([col("b", 20), col("c", 10), col("a", 20)]).map((c) => c.key))
      .toEqual(["c", "a", "b"]);
  });
});

describe("canEditColumnField", () => {
  it("locks destructive system-column fields", () => {
    const system = { is_system: true, scope: "cs" as const, key: "priority" };
    expect(canEditColumnField(system, "label")).toBe(true);
    expect(canEditColumnField(system, "position")).toBe(true);
    expect(canEditColumnField(system, "pinned")).toBe(true);
    expect(canEditColumnField(system, "hidden_default")).toBe(true);
    expect(canEditColumnField(system, "show_in_detail")).toBe(true);
    expect(canEditColumnField(system, "required")).toBe(true);
    expect(canEditColumnField(system, "type")).toBe(false);
    expect(canEditColumnField(system, "archived_at")).toBe(false);
  });

  it("locks 'required' for auto-generated SYSTEM columns", () => {
    const reporter = { is_system: true, scope: "cs" as const, key: "reporter" };
    expect(canEditColumnField(reporter, "required")).toBe(false);
  });

  it("never locks 'required' for a custom column, even if its key coincidentally matches an auto-generated system key", () => {
    const customNamedKey = { is_system: false, scope: "cs" as const, key: "key" };
    expect(canEditColumnField(customNamedKey, "required")).toBe(true);
  });
});

describe("isAutoGeneratedColumn", () => {
  it("flags system columns with no create-time input", () => {
    expect(isAutoGeneratedColumn({ is_system: true, scope: "cs", key: "reporter" })).toBe(true);
    expect(isAutoGeneratedColumn({ is_system: true, scope: "cs", key: "status" })).toBe(true);
    expect(isAutoGeneratedColumn({ is_system: true, scope: "cs", key: "assignee" })).toBe(true);
    expect(isAutoGeneratedColumn({ is_system: true, scope: "aca", key: "createdBy" })).toBe(true);
    expect(isAutoGeneratedColumn({ is_system: true, scope: "medicare", key: "qc" })).toBe(true);
  });

  it("does not flag system columns with a real create-time input", () => {
    expect(isAutoGeneratedColumn({ is_system: true, scope: "cs", key: "agent" })).toBe(false);
    expect(isAutoGeneratedColumn({ is_system: true, scope: "aca", key: "client" })).toBe(false);
  });

  it("never flags custom columns, regardless of key", () => {
    expect(isAutoGeneratedColumn({ is_system: false, scope: "cs", key: "reporter" })).toBe(false);
    expect(isAutoGeneratedColumn({ is_system: false, scope: "cs", key: "anything" })).toBe(false);
  });
});

describe("nextPosition", () => {
  it("increments by ten from the largest position", () => {
    expect(nextPosition([])).toBe(10);
    expect(nextPosition([col("a", 10), col("b", 50)])).toBe(60);
  });
});
