import { describe, expect, it } from "vitest";
import {
  applyColumnPatchInvariants,
  canEditColumnField,
  isAutoGeneratedColumn,
  nextPosition,
  slugifyColumnKey,
  sortColumns,
} from "./columns";
import type { TableColumn } from "./types";

const col = (key: string, position: number, label = key): TableColumn => ({
  id: key,
  scope: "aca",
  key,
  label,
  type: "text",
  is_system: false,
  position,
  pinned: false,
  hidden_default: false,
  show_in_detail: false,
  required: false,
  archived_at: null,
});

describe("slugifyColumnKey", () => {
  it("builds stable snake-case keys", () => {
    expect(slugifyColumnKey("FUB Link 2026!")).toBe("fub_link_2026");
    expect(slugifyColumnKey("   ")).toBe("custom_column");
  });
});

describe("sortColumns", () => {
  it("sorts by position then label then key", () => {
    expect(sortColumns([col("b", 20), col("c", 10), col("a", 20)]).map((c) => c.key))
      .toEqual(["c", "a", "b"]);
  });
});

// These invariants run on BOTH the server (api/config/columns/[id]) and the
// client's optimistic update. If the two ever disagree the toggled row
// visibly corrects itself when the echo lands, which is the bug this shared
// function exists to prevent — so pin the exact behaviour here.
describe("applyColumnPatchInvariants", () => {
  const base = { pinned: false, required: false, is_system: false };

  it("forces hidden_default off when the patch turns Pinned on", () => {
    expect(applyColumnPatchInvariants(base, { pinned: true })).toEqual({
      pinned: true,
      hidden_default: false,
    });
  });

  it("forces hidden_default off AND show_in_detail on for a required custom column", () => {
    expect(applyColumnPatchInvariants(base, { required: true })).toEqual({
      required: true,
      hidden_default: false,
      show_in_detail: true,
    });
  });

  it("does not force show_in_detail for a required SYSTEM column", () => {
    const system = { ...base, is_system: true };
    expect(applyColumnPatchInvariants(system, { required: true })).toEqual({
      required: true,
      hidden_default: false,
    });
  });

  it("reads the column's existing state when the patch omits the flag", () => {
    // Column is already Required; an unrelated patch must still not let it hide.
    const required = { ...base, required: true };
    expect(applyColumnPatchInvariants(required, { hidden_default: true })).toEqual({
      hidden_default: false,
      show_in_detail: true,
    });
  });

  it("leaves an unrelated patch untouched", () => {
    expect(applyColumnPatchInvariants(base, { label: "New" })).toEqual({ label: "New" });
  });

  it("allows turning Pinned off without forcing anything", () => {
    const pinned = { ...base, pinned: true };
    expect(applyColumnPatchInvariants(pinned, { pinned: false })).toEqual({
      pinned: false,
    });
  });

  it("does not mutate the caller's patch object", () => {
    const patch = { required: true };
    applyColumnPatchInvariants(base, patch);
    expect(patch).toEqual({ required: true });
  });
});

describe("canEditColumnField", () => {
  it("locks destructive system-column fields", () => {
    const system = { is_system: true, scope: "cs" as const, key: "priority" };
    expect(canEditColumnField(system, "label")).toBe(true);
    expect(canEditColumnField(system, "position")).toBe(true);
    expect(canEditColumnField(system, "pinned")).toBe(true);
    expect(canEditColumnField(system, "hidden_default")).toBe(true);
    expect(canEditColumnField(system, "show_in_detail")).toBe(true);
    expect(canEditColumnField(system, "required")).toBe(true);
    expect(canEditColumnField(system, "type")).toBe(false);
    expect(canEditColumnField(system, "archived_at")).toBe(false);
  });

  it("locks 'required' for auto-generated SYSTEM columns", () => {
    const reporter = { is_system: true, scope: "cs" as const, key: "reporter" };
    expect(canEditColumnField(reporter, "required")).toBe(false);
  });

  it("never locks 'required' for a custom column, even if its key coincidentally matches an auto-generated system key", () => {
    const customNamedKey = { is_system: false, scope: "cs" as const, key: "key" };
    expect(canEditColumnField(customNamedKey, "required")).toBe(true);
  });
});

describe("isAutoGeneratedColumn", () => {
  it("flags system columns with no create-time input", () => {
    expect(isAutoGeneratedColumn({ is_system: true, scope: "cs", key: "reporter" })).toBe(true);
    expect(isAutoGeneratedColumn({ is_system: true, scope: "cs", key: "status" })).toBe(true);
    expect(isAutoGeneratedColumn({ is_system: true, scope: "cs", key: "assignee" })).toBe(true);
    expect(isAutoGeneratedColumn({ is_system: true, scope: "aca", key: "createdBy" })).toBe(true);
    expect(isAutoGeneratedColumn({ is_system: true, scope: "aca", key: "timeProgress" })).toBe(true);
    expect(isAutoGeneratedColumn({ is_system: true, scope: "medicare", key: "timeProgress" })).toBe(true);
    expect(isAutoGeneratedColumn({ is_system: true, scope: "medicare", key: "qc" })).toBe(true);
  });

  it("does not flag system columns with a real create-time input", () => {
    expect(isAutoGeneratedColumn({ is_system: true, scope: "cs", key: "agent" })).toBe(false);
    expect(isAutoGeneratedColumn({ is_system: true, scope: "aca", key: "client" })).toBe(false);
  });

  it("never flags custom columns, regardless of key", () => {
    expect(isAutoGeneratedColumn({ is_system: false, scope: "cs", key: "reporter" })).toBe(false);
    expect(isAutoGeneratedColumn({ is_system: false, scope: "cs", key: "anything" })).toBe(false);
  });
});

describe("nextPosition", () => {
  it("increments by ten from the largest position", () => {
    expect(nextPosition([])).toBe(10);
    expect(nextPosition([col("a", 10), col("b", 50)])).toBe(60);
  });
});
