import type { TableColumn, TableScope } from "./types";

export type EditableColumnField =
  | "label"
  | "type"
  | "position"
  | "pinned"
  | "hidden_default"
  | "show_in_detail"
  | "required"
  | "archived_at";

export function slugifyColumnKey(label: string): string {
  const normalized = label
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
  return normalized || "custom_column";
}

export function sortColumns<T extends Pick<TableColumn, "position" | "label" | "key">>(
  columns: readonly T[]
): T[] {
  return [...columns].sort(
    (a, b) =>
      a.position - b.position ||
      a.label.localeCompare(b.label) ||
      a.key.localeCompare(b.key)
  );
}

// Invariants the server enforces on every column PATCH. Exported so the
// client's optimistic update applies the SAME derived fields the server will,
// instead of showing a partial state that visibly corrects itself ~1s later
// when the echo arrives (e.g. "In detail" switching itself on after you set
// Required). Server and client must call this one function — duplicating the
// rules is how they drift.
export function applyColumnPatchInvariants(
  column: Pick<TableColumn, "pinned" | "required" | "is_system">,
  patch: Record<string, unknown>
): Record<string, unknown> {
  const next = { ...patch };
  const willBePinned = "pinned" in next ? next.pinned === true : column.pinned;
  const willBeRequired = "required" in next ? next.required === true : column.required;
  // Required/Pinned fields must always reach the form, so they can never be Hidden.
  if (willBePinned || willBeRequired) next.hidden_default = false;
  // Required means "must appear on the form", which is meaningless for a
  // custom column if its form opt-in is off.
  if (willBeRequired && !column.is_system) next.show_in_detail = true;
  return next;
}

// The ONLY thing this list encodes is "does this system column key have a
// real, editable Create-time input at all" — it does NOT translate key names
// to request/DB field names. Callers building a Required-check payload key
// their object with these SAME table_column.key strings directly (e.g.
// `{ summary: title, category: categoryId, agent: agentEmail }`), so there is
// no separate translation table anywhere that could drift out of sync with
// the DB — findMissingRequiredFields() in required.ts reads column.key
// straight off the live table_column row and looks up that exact key in
// whatever object the caller passed.
//
// Custom columns are never excluded — any custom column is always Required-
// capable, since every custom column that's editable at all goes through the
// generic custom_values path (keyed by column.key already, no translation
// needed there either).
export const REQUIRED_CAPABLE_SYSTEM_KEYS: Record<TableScope, ReadonlySet<string>> = {
  cs: new Set(["summary", "description", "fub", "priority", "category", "agent"]),
  aca: new Set([
    "client", "description", "fub", "due", "stage", "carrier", "platform",
    "consent", "payment", "aca", "pcp2025", "pcp2026", "agent", "caller", "responsible",
  ]),
  medicare: new Set([
    "client", "description", "fub", "due", "stage", "carrier", "pcp2025", "agent", "responsible",
  ]),
  // "assignee" (cs) is deliberately absent from that set: an unassigned task
  // is a valid, intentional state in this system (unassigning is what sends
  // a task back to Backlog — see StatusPill's comment in TaskRowItem.tsx),
  // not a missing value. Required's "must be non-empty" semantic would
  // directly contradict that, so Assignee can't be marked Required at all.
};

export function isAutoGeneratedColumn(
  column: Pick<TableColumn, "scope" | "key" | "is_system">
): boolean {
  if (!column.is_system) return false;
  return !(REQUIRED_CAPABLE_SYSTEM_KEYS[column.scope]?.has(column.key) ?? false);
}

export function canEditColumnField(
  column: Pick<TableColumn, "is_system" | "scope" | "key">,
  field: EditableColumnField
): boolean {
  if (field === "required" && isAutoGeneratedColumn(column)) return false;
  if (!column.is_system) return true;
  return (
    field === "label" ||
    field === "position" ||
    field === "pinned" ||
    field === "hidden_default" ||
    field === "show_in_detail" ||
    field === "required"
  );
}

export function nextPosition(columns: readonly Pick<TableColumn, "position">[]): number {
  if (columns.length === 0) return 10;
  return Math.max(...columns.map((column) => column.position)) + 10;
}
