"use client";

import { createPortal } from "react-dom";
import { useEffect, useId, useMemo, useRef, useState } from "react";
import type { Dispatch, ReactNode, SetStateAction } from "react";
import {
  closestCenter,
  DndContext,
  KeyboardSensor,
  PointerSensor,
  useSensor,
  useSensors,
  type DragEndEvent,
} from "@dnd-kit/core";
import {
  arrayMove,
  SortableContext,
  sortableKeyboardCoordinates,
  useSortable,
  verticalListSortingStrategy,
} from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import {
  ChevronDown,
  Clock,
  GripVertical,
  Info,
  Plus,
  RefreshCw,
  Settings2,
  SlidersHorizontal,
  Trash2,
  UserRoundCog,
} from "lucide-react";
import { Toast, type ToastTone } from "../../_shared/Toast";
import { SearchableListboxPanel } from "../../_shared/SearchableListboxPanel";
import { useAnchoredMenu } from "../../tasks/_components/use-anchored-menu";
import type { TaskAgent, TaskAssignee } from "@/lib/tasks/assignees";
import type { TaskCategory, TaskSlaRule } from "@/lib/tasks/types";
import {
  COLUMN_TYPES,
  TABLE_SCOPES,
  type ColumnType,
  type TableColumn,
  type TableColumnOption,
  type TableScope,
  isColumnType,
} from "@/lib/table-config/types";
import {
  applyColumnPatchInvariants,
  isAutoGeneratedColumn,
  sortColumns,
} from "@/lib/table-config/columns";
import { validateColumnOrderRequest } from "@/lib/table-config/column-order";
import {
  emptyEnrollmentOptionsBySet,
  sortEnrollmentOptionsByLabel,
  type EnrollmentOptionsBySet,
} from "@/lib/enrollment/options";
import type {
  EnrollmentOption,
  EnrollmentOptionSet,
  EnrollmentOptionSetKey,
} from "@/lib/enrollment/types";
import {
  enrollmentIdentityBadgeStyle,
  enrollmentStateBadgeStyle,
} from "@/lib/enrollment/option-badge";
import {
  nextRecommendedDropdownValueColor,
  recommendDropdownValueColor,
  tableColumnOptionBadgePalette,
} from "@/lib/table-config/value-colors";
import { ConfigSlaSection } from "./ConfigSlaSection";
import { isConfigMutationWarning } from "@/lib/table-config/partial-success";
import { isLatestRefresh, readRefreshResponse } from "@/lib/table-config/refresh-state";

type AssistantMember = {
  agent_email: string;
  cs_email: string;
  is_assistant: boolean;
};

type Tab = "table" | "value" | "assistant" | "sla";
type SelectOption<T extends string> = { value: T; label: string; disabled?: boolean };

const SCOPE_LABEL: Record<TableScope, string> = {
  cs: "Health Customer Service",
  aca: "Health ACA Enrollment",
  medicare: "Health Medicare Enrollment",
};

const SCOPE_OPTIONS: SelectOption<TableScope>[] = TABLE_SCOPES.map((scope) => ({
  value: scope,
  label: SCOPE_LABEL[scope],
}));

const COLUMN_TYPE_LABEL: Record<ColumnType, string> = {
  text: "Text",
  number: "Number",
  dropdown: "Dropdown",
  date: "Date",
  checkbox: "Yes/No",
  link: "Link",
  person: "Person",
};

const COLUMN_TYPE_OPTIONS: SelectOption<ColumnType>[] = COLUMN_TYPES.map((type) => ({
  value: type,
  label: COLUMN_TYPE_LABEL[type],
}));

type EnrollmentOptionData = {
  sets: EnrollmentOptionSet[];
  options: EnrollmentOption[];
  optionsBySet: EnrollmentOptionsBySet;
};

export type ConfigSectionStatus = {
  available: boolean;
  error?: string;
};

type ConfigSectionStatuses = {
  columns: ConfigSectionStatus;
  options: ConfigSectionStatus;
  categories: ConfigSectionStatus;
  assistants: ConfigSectionStatus;
  sla: ConfigSectionStatus;
  enrollmentOptions: Record<"aca" | "medicare", ConfigSectionStatus>;
};

export function ConfigClient({
  initialColumns,
  initialOptions,
  initialAgents,
  candidates,
  assignees,
  initialMembers,
  initialCategories,
  initialSlaRules,
  initialOptionData,
  sectionStatus,
}: {
  initialColumns: Record<TableScope, TableColumn[]>;
  initialOptions: Record<TableScope, TableColumnOption[]>;
  initialAgents: TaskAgent[];
  candidates: TaskAssignee[];
  assignees: TaskAssignee[];
  initialMembers: AssistantMember[];
  initialCategories: TaskCategory[];
  initialSlaRules: TaskSlaRule[];
  initialOptionData: Record<"aca" | "medicare", EnrollmentOptionData>;
  sectionStatus: ConfigSectionStatuses;
}) {
  const [tab, setTab] = useState<Tab>("table");
  const [scope, setScope] = useState<TableScope>("cs");
  const [columns, setColumns] = useState(initialColumns);
  const [options, setOptions] = useState(initialOptions);
  const [agents, setAgents] = useState(initialAgents);
  const [members, setMembers] = useState(initialMembers);
  const [categories, setCategories] = useState(initialCategories);
  const [slaRules, setSlaRules] = useState(initialSlaRules);
  const [optionData, setOptionData] = useState(initialOptionData);
  const [notice, setNotice] = useState<string | null>(null);
  const [noticeTone, setNoticeTone] = useState<ToastTone>("info");
  const [busy, setBusy] = useState(false);
  const [refreshErrors, setRefreshErrors] = useState<Record<string, string | undefined>>({});
  const scopeRefreshSequenceRef = useRef(new Map<TableScope, number>());
  const optionRefreshSequenceRef = useRef(new Map<"aca" | "medicare", number>());

  function setRefreshError(key: string, error?: string) {
    setRefreshErrors((current) => {
      const next = { ...current };
      if (error) next[key] = error;
      else delete next[key];
      return next;
    });
  }

  async function refreshScope(nextScope = scope) {
    const requestSequence = (scopeRefreshSequenceRef.current.get(nextScope) ?? 0) + 1;
    scopeRefreshSequenceRef.current.set(nextScope, requestSequence);
    const columnsKey = `columns:${nextScope}`;
    const optionsKey = `options:${nextScope}`;
    try {
      const response = await fetch(`/api/config/columns?scope=${nextScope}`, {
        cache: "no-store",
      });
      const payload = await readRefreshResponse<unknown>(
        response,
        `Could not refresh ${SCOPE_LABEL[nextScope]} columns.`
      );
      if (!isLatestRefresh(requestSequence, scopeRefreshSequenceRef.current.get(nextScope) ?? 0)) return;
      if (!payload || typeof payload !== "object" || !Array.isArray((payload as { columns?: unknown }).columns) || !Array.isArray((payload as { options?: unknown }).options)) {
        throw new Error(`Could not refresh ${SCOPE_LABEL[nextScope]} columns.`);
      }
      setColumns((current) => ({ ...current, [nextScope]: (payload as { columns: TableColumn[] }).columns }));
      setOptions((current) => ({ ...current, [nextScope]: (payload as { options: TableColumnOption[] }).options }));
      setRefreshError(columnsKey);
      setRefreshError(optionsKey);
    } catch (error) {
      if (!isLatestRefresh(requestSequence, scopeRefreshSequenceRef.current.get(nextScope) ?? 0)) return;
      const message = error instanceof Error ? error.message : `Could not refresh ${SCOPE_LABEL[nextScope]} columns.`;
      setRefreshError(columnsKey, message);
      setRefreshError(optionsKey, message);
      throw error;
    }
  }

  async function refreshOptionData(program: "aca" | "medicare") {
    const requestSequence = (optionRefreshSequenceRef.current.get(program) ?? 0) + 1;
    optionRefreshSequenceRef.current.set(program, requestSequence);
    const key = `enrollment-options:${program}`;
    try {
      const response = await fetch(`/api/enrollment/option-sets?program=${program}`, {
        cache: "no-store",
      });
      const data = await readRefreshResponse<unknown>(
        response,
        `Could not refresh ${program.toUpperCase()} enrollment options.`
      );
      if (!isLatestRefresh(requestSequence, optionRefreshSequenceRef.current.get(program) ?? 0)) return;
      if (!data || typeof data !== "object" || !Array.isArray((data as EnrollmentOptionData).sets) || !Array.isArray((data as EnrollmentOptionData).options) || !((data as EnrollmentOptionData).optionsBySet && typeof (data as EnrollmentOptionData).optionsBySet === "object")) {
        throw new Error(`Could not refresh ${program.toUpperCase()} enrollment options.`);
      }
      setOptionData((current) => ({ ...current, [program]: data as EnrollmentOptionData }));
      setRefreshError(key);
    } catch (error) {
      if (!isLatestRefresh(requestSequence, optionRefreshSequenceRef.current.get(program) ?? 0)) return;
      setRefreshError(key, error instanceof Error ? error.message : `Could not refresh ${program.toUpperCase()} enrollment options.`);
      throw error;
    }
  }

  async function run(action: () => Promise<unknown>, success: string) {
    setBusy(true);
    setNotice(null);
    setNoticeTone("info");
    try {
      const result = await action();
      const warnings =
        result && typeof result === "object" && "warnings" in result && Array.isArray(result.warnings)
          ? result.warnings
              .map((warning) =>
                typeof warning === "string"
                  ? warning
                  : isConfigMutationWarning(warning)
                    ? warning.message
                    : null
              )
              .filter((warning): warning is string => Boolean(warning))
          : [];
      setNoticeTone(warnings.length > 0 ? "info" : "success");
      setNotice(warnings.length > 0 ? warnings.join(" ") : success);
    } catch (error) {
      setNoticeTone("error");
      setNotice(error instanceof Error ? error.message : "Something went wrong.");
    } finally {
      setBusy(false);
    }
  }

  const activeColumns = columns[scope] ?? [];
  const activeOptions = options[scope] ?? [];
  const columnsRefreshError = refreshErrors[`columns:${scope}`];
  const optionsRefreshError = refreshErrors[`options:${scope}`];
  const enrollmentOptionsRefreshError =
    scope === "aca" || scope === "medicare" ? refreshErrors[`enrollment-options:${scope}`] : undefined;

  return (
    <main className="min-h-screen bg-[#f7f8fa] px-6 pb-6 pt-5 text-[#172b4d]">
      <div className="mx-auto flex max-w-[1280px] flex-col gap-6">
        <header className="flex flex-wrap items-end justify-between gap-4">
          <div>
            <h1 className="text-3xl font-bold leading-tight tracking-normal text-[#172b4d]">
              Health Table Configuration
            </h1>
          </div>
          <DropdownSelect
            label="Table"
            value={scope}
            options={SCOPE_OPTIONS}
            onChange={setScope}
            className="w-[330px]"
            buttonClassName="h-11 shadow-sm"
          />
        </header>

        <div className="flex w-fit rounded border border-[#dfe3ea] bg-[#f4f5f7] p-0.5 shadow-sm">
          <TabButton active={tab === "table"} onClick={() => setTab("table")}>
            <Settings2 className="h-4 w-4" /> Columns
          </TabButton>
          <TabButton active={tab === "value"} onClick={() => setTab("value")}>
            <SlidersHorizontal className="h-4 w-4" /> Dropdown Values
          </TabButton>
          <TabButton active={tab === "assistant"} onClick={() => setTab("assistant")}>
            <UserRoundCog className="h-4 w-4" /> Assistant Membership
          </TabButton>
          <TabButton active={tab === "sla"} onClick={() => setTab("sla")}>
            <Clock className="h-4 w-4" /> SLA Times
          </TabButton>
        </div>

        {tab === "table" ? (
          <ConfigTableSection
            key={scope}
            scope={scope}
            columns={activeColumns}
            busy={busy}
            available={sectionStatus.columns.available && !columnsRefreshError}
            availabilityError={columnsRefreshError ?? sectionStatus.columns.error}
            run={run}
            refreshScope={refreshScope}
          />
        ) : null}
        {tab === "value" ? (
          <ConfigDropdownValuesSection
            key={scope}
            scope={scope}
            columns={activeColumns}
            options={activeOptions}
            categories={categories}
            optionSets={scope === "aca" || scope === "medicare" ? optionData[scope].sets : []}
            optionsBySet={
              scope === "aca" || scope === "medicare"
                ? optionData[scope].optionsBySet
                : emptyEnrollmentOptionsBySet()
            }
            busy={busy}
            available={
              sectionStatus.options.available &&
              !optionsRefreshError &&
              (scope === "cs"
                ? true
                : sectionStatus.enrollmentOptions[scope].available && !enrollmentOptionsRefreshError)
            }
            availabilityError={
              optionsRefreshError ??
              enrollmentOptionsRefreshError ??
              sectionStatus.options.error ??
              (scope === "cs" ? undefined : sectionStatus.enrollmentOptions[scope].error)
            }
            categoriesAvailable={sectionStatus.categories.available}
            categoriesError={sectionStatus.categories.error}
            run={run}
            refreshScope={refreshScope}
            onCategoriesChange={setCategories}
            onOptionDataChange={() =>
              scope === "aca" || scope === "medicare" ? refreshOptionData(scope) : Promise.resolve()
            }
          />
        ) : null}
        {tab === "assistant" ? (
          <ConfigAssistantSection
            agents={agents}
            candidates={candidates}
            assignees={assignees}
            members={members}
            busy={busy}
            available={sectionStatus.assistants.available}
            availabilityError={sectionStatus.assistants.error}
            run={run}
            setMembers={setMembers}
            onAgentsChange={setAgents}
          />
        ) : null}
        {tab === "sla" ? (
          <ConfigSlaSection
            categories={categories}
            rules={slaRules}
            available={sectionStatus.sla.available}
            availabilityError={sectionStatus.sla.error}
            onRulesChange={setSlaRules}
          />
        ) : null}
      </div>

      <Toast
        message={notice}
        tone={noticeTone}
        onDismiss={() => setNotice(null)}
      />
    </main>
  );
}

function TabButton({
  active,
  onClick,
  children,
}: {
  active: boolean;
  onClick: () => void;
  children: ReactNode;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={`inline-flex items-center gap-2 rounded px-3 py-1.5 text-sm font-semibold transition ${
        active
          ? "bg-white text-[#0c66e4] shadow-sm ring-1 ring-[#d8dee7]"
          : "text-[#44546f] hover:bg-white/70 hover:text-[#172b4d]"
      }`}
    >
      {children}
    </button>
  );
}

function ColumnHeader({ label, help }: { label: string; help: string }) {
  return (
    <span
      className="inline-flex min-w-0 items-center gap-1 whitespace-nowrap"
      title={help}
      aria-label={`${label}: ${help}`}
    >
      <span className="truncate">{label}</span>
      <Info aria-hidden="true" className="h-3.5 w-3.5 shrink-0 text-[#8993a4]" />
    </span>
  );
}

function ConfigSectionUnavailable({ message }: { message?: string }) {
  return (
    <div
      className="mx-4 mt-4 rounded border border-[#ffab00] bg-[#fff7d6] px-4 py-3 text-sm font-semibold text-[#7f5f00]"
      role="status"
    >
      {message ?? "This section is temporarily unavailable. Editing is disabled."}
    </div>
  );
}

function DropdownSelect<T extends string>({
  label,
  value,
  options,
  onChange,
  placeholder = "Select",
  className = "",
  buttonClassName = "",
}: {
  label: string;
  value: T;
  options: SelectOption<T>[];
  onChange: (value: T) => void;
  placeholder?: string;
  className?: string;
  buttonClassName?: string;
}) {
  const {
    isOpen,
    toggle,
    triggerRef,
    menuRef,
    menuStyle,
    closeMenu,
    closeMenuForTab,
  } = useAnchoredMenu();
  const selected = options.find((option) => option.value === value);

  return (
    <div className={`relative ${className}`}>
      <button
        ref={triggerRef}
        type="button"
        aria-label={label}
        aria-haspopup="listbox"
        aria-expanded={isOpen}
        onClick={toggle}
        className={`flex h-10 w-full items-center justify-between gap-3 rounded border border-[#dfe1e6] bg-white px-3 text-left text-sm font-semibold text-[#172b4d] shadow-sm outline-none transition hover:border-[#b8c7dc] focus:border-[#0c66e4] focus:ring-2 focus:ring-[#0c66e4]/20 ${buttonClassName}`}
      >
        <span className={`truncate ${selected ? "" : "text-[#97a0af]"}`}>
          {selected?.label ?? placeholder}
        </span>
        <ChevronDown
          className={`h-4 w-4 shrink-0 text-[#6b778c] transition ${isOpen ? "rotate-180" : ""}`}
          aria-hidden="true"
        />
      </button>

      {isOpen
        ? createPortal(
            <SearchableListboxPanel
              menuRef={menuRef}
              menuStyle={menuStyle}
              className="min-w-[16rem]"
              ariaLabel={label}
              queryPlaceholder={`Search ${label.toLowerCase()}…`}
              emptyMessage="No matching options."
              choices={options.map((option) => ({
                value: option.value,
                label: option.label,
                disabled: option.disabled,
              }))}
              selectedValue={value}
              onSelect={(nextValue) => {
                onChange(nextValue as T);
                closeMenu({ restoreFocus: true });
              }}
              onTabExit={closeMenuForTab}
            />,
            document.body
          )
        : null}
    </div>
  );
}

function ConfigTableSection({
  scope,
  columns,
  busy,
  available,
  availabilityError,
  run,
  refreshScope,
}: {
  scope: TableScope;
  columns: TableColumn[];
  busy: boolean;
  available: boolean;
  availabilityError?: string;
  run: (action: () => Promise<unknown>, success: string) => Promise<void>;
  refreshScope: (scope?: TableScope) => Promise<void>;
}) {
  const [newLabel, setNewLabel] = useState("");
  const [newType, setNewType] = useState<ColumnType>("text");
  const [dragReady, setDragReady] = useState(false);
  const [confirmArchiveColumnId, setConfirmArchiveColumnId] = useState<string | null>(null);
  const [restoreColumnCandidate, setRestoreColumnCandidate] = useState<{
    id: string;
    label: string;
    type: ColumnType;
  } | null>(null);
  // Counts column PATCHes still in flight. Only the last one to settle
  // refreshes from the server — see patchColumn for why.
  const pendingColumnPatchesRef = useRef(0);
  // PATCHes for one column must be sent in intent order. Otherwise an older
  // response/failure can overwrite a newer optimistic toggle or skip the
  // final canonical refresh entirely.
  const columnPatchQueuesRef = useRef(new Map<string, Promise<void>>());
  // Plain position order — the editor deliberately does NOT sink hidden
  // columns to the bottom. It used to, and that made toggling Hidden teleport
  // the row out from under the cursor (rows only animate while dnd-kit is
  // dragging), so the switch you just clicked was replaced mid-interaction by
  // a different column's switch and read as "the toggle did nothing". It also
  // corrupted data: handleDragEnd writes `position: index + 1` from the
  // editor order, so any drag baked the hidden-sink into real positions and
  // un-hiding later left the column stranded at the bottom. Hidden rows are
  // marked visually instead.
  const sortedColumns = useMemo(() => sortColumns(columns), [columns]);
  const [localColumns, setLocalColumns] = useState(sortedColumns);
  const sensors = useSensors(
    useSensor(PointerSensor, { activationConstraint: { distance: 5 } }),
    useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates })
  );

  useEffect(() => {
    const timer = window.setTimeout(() => setLocalColumns(sortedColumns), 0);
    return () => window.clearTimeout(timer);
  }, [sortedColumns]);

  useEffect(() => {
    const timer = window.setTimeout(() => setDragReady(true), 0);
    return () => window.clearTimeout(timer);
  }, []);

  function patchSuccessMessage(patch: Record<string, unknown>): string {
    // hidden_default/pinned resets everyone's saved layout server-side (see
    // resetTableLayoutsForScope) so the admin's change actually takes effect
    // for users who already customized this table — say so explicitly.
    return "hidden_default" in patch || "pinned" in patch
      ? "Column visibility updated for everyone."
      : "Column updated.";
  }

  async function updateColumn(id: string, patch: Record<string, unknown>) {
    if (!available) throw new Error(availabilityError ?? "Table columns are unavailable.");
    await requestJson(`/api/config/columns/${id}`, {
      method: "PATCH",
      body: JSON.stringify(patch),
    });
  }

  async function patchColumn(id: string, patch: Record<string, unknown>) {
    if (!available) return;
    setLocalColumns((current) =>
      current.map((column) => {
        if (column.id !== id) return column;
        // Apply the SAME derived fields the server will, so the optimistic
        // row already matches the echo. Without this the UI visibly corrects
        // itself ~1s later (e.g. "In detail" switching itself on after you
        // set Required). Row ORDER is deliberately left alone — see the
        // sortedColumns comment above.
        return { ...column, ...applyColumnPatchInvariants(column, patch) } as TableColumn;
      })
    );
    pendingColumnPatchesRef.current += 1;
    const previous = columnPatchQueuesRef.current.get(id) ?? Promise.resolve();
    const operation = previous
      .catch(() => undefined)
      .then(async () => {
        try {
          await updateColumn(id, patch);
        } finally {
          pendingColumnPatchesRef.current -= 1;
          // Reconcile even when the final PATCH fails. Without this in
          // finally, the optimistic value can remain visible while the
          // server still holds the previous canonical value.
          if (pendingColumnPatchesRef.current === 0) {
            await refreshScope(scope);
          }
        }
      });
    columnPatchQueuesRef.current.set(id, operation);
    try {
      await operation;
    } finally {
      if (columnPatchQueuesRef.current.get(id) === operation) {
        columnPatchQueuesRef.current.delete(id);
      }
    }
  }

  function handleDragEnd(event: DragEndEvent) {
    if (!available) return;
    const { active, over } = event;
    if (!over || active.id === over.id) return;

    const oldIndex = localColumns.findIndex((column) => column.id === active.id);
    const newIndex = localColumns.findIndex((column) => column.id === over.id);
    if (oldIndex === -1 || newIndex === -1 || oldIndex === newIndex) return;

    const expectedColumnKeys = localColumns.map((column) => column.key);
    const nextColumns = arrayMove(localColumns, oldIndex, newIndex).map(
      (column, index) => ({ ...column, position: index + 1 })
    );
    const orderRequest = validateColumnOrderRequest(
      expectedColumnKeys,
      nextColumns.map((column) => column.key)
    );
    if (!orderRequest.ok) return;
    setLocalColumns(nextColumns);

    void run(async () => {
      try {
        return await requestJson("/api/config/columns/reorder", {
          method: "POST",
          body: JSON.stringify({
            scope,
            expected_column_keys: orderRequest.request.expectedColumnKeys,
            column_keys: orderRequest.request.columnKeys,
          }),
        });
      } finally {
        // A stale 409 must never leave an optimistic order visible after the
        // server has accepted another writer's order.
        await refreshScope(scope);
      }
    }, "Column order updated for everyone.");
  }

  const confirmArchiveColumn =
    localColumns.find((column) => column.id === confirmArchiveColumnId) ?? null;

  function archiveConfirmedColumn() {
    if (!confirmArchiveColumn) return;
    const columnId = confirmArchiveColumn.id;
    setConfirmArchiveColumnId(null);
    void run(async () => {
      await requestJson(`/api/config/columns/${columnId}`, { method: "DELETE" });
      await refreshScope(scope);
    }, "Column archived.");
  }

  return (
    <>
    <section className="overflow-hidden rounded border border-[#dfe1e6] bg-white shadow-sm">
      <div className="border-b border-[#dfe1e6] px-6 py-4">
        <h2 className="text-lg font-bold">Column settings for {SCOPE_LABEL[scope]}</h2>
      </div>
      {!available ? <ConfigSectionUnavailable message={availabilityError} /> : null}
      <form
        className="flex flex-wrap items-center gap-3 border-b border-[#dfe1e6] bg-[#fafbfc] p-4"
        onSubmit={(event) => {
          event.preventDefault();
          void run(async () => {
            try {
              await requestJson("/api/config/columns", {
                method: "POST",
                body: JSON.stringify({ scope, label: newLabel, type: newType }),
              });
            } catch (error) {
              if (
                error instanceof Error &&
                (error as RequestJsonError).code === "CONFIG_ARCHIVED_COLUMN_EXISTS" &&
                isColumnType((error as RequestJsonError).payload?.archived_column?.type) &&
                typeof (error as RequestJsonError).payload?.archived_column?.id === "string" &&
                typeof (error as RequestJsonError).payload?.archived_column?.label === "string"
              ) {
                const archived = (error as RequestJsonError).payload!.archived_column!;
                setRestoreColumnCandidate({
                  id: archived.id as string,
                  label: archived.label as string,
                  type: archived.type as ColumnType,
                });
                throw new Error(
                  `An archived column named "${archived.label}" already exists. Confirm restore to bring back its saved options and settings.`
                );
              }
              throw error;
            }
            setNewLabel("");
            await refreshScope(scope);
          }, "Column added.");
        }}
      >
        <input
          value={newLabel}
          onChange={(event) => setNewLabel(event.target.value)}
          placeholder="New column label"
          className="h-10 min-w-[280px] max-w-[520px] flex-1 rounded border border-[#dfe1e6] bg-white px-3 text-sm font-semibold text-[#172b4d] outline-none placeholder:text-[#97a0af] focus:border-[#0c66e4]"
        />
        <DropdownSelect
          label="Column type"
          value={newType}
          options={COLUMN_TYPE_OPTIONS}
          onChange={setNewType}
          className="w-[200px]"
        />
        <button
          type="submit"
          disabled={busy || !available || !newLabel.trim()}
          className="inline-flex h-10 w-[140px] items-center justify-center gap-2 rounded bg-[#0c66e4] px-4 text-sm font-bold text-white disabled:opacity-50"
        >
          <Plus className="h-4 w-4" /> Add
        </button>
      </form>
      <div className="min-w-0 overflow-x-auto">
        <div className="min-w-[1016px]">
          <div className="grid grid-cols-[112px_minmax(240px,1fr)_120px_104px_104px_104px_112px_120px] border-b border-[#dfe1e6] bg-[#fafbfc] px-4 py-2 text-xs font-bold uppercase tracking-wide text-[#6b778c]">
            <ColumnHeader label="Display order" help="Drag a row to change its position in the table." />
            <ColumnHeader label="Column label" help="The name users see for this column." />
            <ColumnHeader label="Data type" help="Controls how values are stored, displayed, and edited." />
            <ColumnHeader label="Pin to left" help="Keep this column visible while horizontally scrolling." />
            <ColumnHeader label="Required on create" help="Require a value when creating a new record." />
            <ColumnHeader label="Hidden by default" help="Hide this column from the table by default." />
            <ColumnHeader label="Show in details" help="Include this column in the record detail view." />
            <ColumnHeader label="Manage" help="Archive or restore custom columns." />
          </div>
          {dragReady ? (
            <DndContext
              id="config-table-columns"
              sensors={sensors}
              collisionDetection={closestCenter}
              onDragEnd={handleDragEnd}
            >
              <SortableContext
                items={localColumns.map((column) => column.id)}
                strategy={verticalListSortingStrategy}
              >
                {localColumns.map((column, index) => (
                  <SortableColumnRow
                    key={column.id}
                    column={column}
                    scope={scope}
                    index={index}
                    busy={busy || !available}
                    onPatch={(patch) =>
                      run(() => patchColumn(column.id, patch), patchSuccessMessage(patch))
                    }
                    onArchive={() => setConfirmArchiveColumnId(column.id)}
                  />
                ))}
              </SortableContext>
            </DndContext>
          ) : (
            <div>
              {localColumns.map((column, index) => (
                <StaticColumnRow
                  key={column.id}
                  column={column}
                  scope={scope}
                  index={index}
                  busy={busy || !available}
                  onPatch={(patch) =>
                    run(() => patchColumn(column.id, patch), patchSuccessMessage(patch))
                  }
                  onArchive={() => setConfirmArchiveColumnId(column.id)}
                />
              ))}
            </div>
          )}
        </div>
      </div>
    </section>
    {confirmArchiveColumn ? (
      <ConfirmDialog
        title={`Archive "${confirmArchiveColumn.label}"?`}
        description="The column will stop appearing anywhere in Create, Detail, List, and Board. This can't be undone from the UI."
        confirmLabel="Archive"
        busy={busy}
        onCancel={() => setConfirmArchiveColumnId(null)}
        onConfirm={archiveConfirmedColumn}
      />
    ) : null}
    {restoreColumnCandidate ? (
      <ConfirmDialog
        title={`Restore "${restoreColumnCandidate.label}"?`}
        description={`This restores the archived ${restoreColumnCandidate.type} column with its existing options and settings. Saved table layouts will be reset so every user can see the restored column.`}
        confirmLabel="Restore column"
        busy={busy}
        onCancel={() => setRestoreColumnCandidate(null)}
        onConfirm={() => {
          const candidate = restoreColumnCandidate;
          setRestoreColumnCandidate(null);
          void run(
            () =>
              requestJson("/api/config/columns", {
                method: "POST",
                body: JSON.stringify({
                  scope,
                  type: candidate.type,
                  restore: true,
                  archived_column_id: candidate.id,
                }),
              }).then(async (payload) => {
                setNewLabel("");
                await refreshScope(scope);
                return payload;
              }),
            "Column restored."
          );
        }}
      />
    ) : null}
    </>
  );
}

function ToggleSwitch({
  checked,
  disabled,
  title,
  onChange,
}: {
  checked: boolean;
  disabled?: boolean;
  title?: string;
  onChange: (next: boolean) => void;
}) {
  return (
    <button
      type="button"
      role="switch"
      aria-checked={checked}
      disabled={disabled}
      title={title}
      onClick={() => onChange(!checked)}
      className={`relative inline-flex h-5 w-9 shrink-0 items-center rounded-full transition-colors disabled:cursor-not-allowed disabled:opacity-40 ${
        checked ? "bg-[#0c66e4]" : "bg-[#c1c7d0]"
      }`}
    >
      <span
        className={`inline-block h-4 w-4 transform rounded-full bg-white shadow transition-transform ${
          checked ? "translate-x-4" : "translate-x-0.5"
        }`}
      />
    </button>
  );
}

function requiredColumnTitle(
  column: Pick<TableColumn, "is_system" | "scope" | "key">,
  scope: TableScope
): string | undefined {
  if (isAutoGeneratedColumn(column)) {
    return "This column has no create-time input, so Required has nothing to check.";
  }
  if (!column.is_system && (scope === "aca" || scope === "medicare")) {
    return "Create does not render custom inputs yet; Required is checked only when a supported flow supplies this custom value.";
  }
  return undefined;
}

function SortableColumnRow({
  column,
  scope,
  index,
  busy,
  onPatch,
  onArchive,
}: {
  column: TableColumn;
  scope: TableScope;
  index: number;
  busy: boolean;
  onPatch: (patch: Record<string, unknown>) => Promise<void>;
  onArchive: () => void;
}) {
  const {
    attributes,
    listeners,
    setActivatorNodeRef,
    setNodeRef,
    transform,
    transition,
    isDragging,
  } = useSortable({ id: column.id, disabled: busy });
  const dragAttributes = { ...attributes };
  delete (dragAttributes as Record<string, unknown>)["aria-describedby"];

  return (
    <div
      ref={setNodeRef}
      style={{
        transform: CSS.Transform.toString(transform),
        transition,
        zIndex: isDragging ? 20 : undefined,
      }}
      className={`grid grid-cols-[112px_minmax(240px,1fr)_120px_104px_104px_104px_112px_120px] items-center border-b border-[#ebecf0] px-4 py-2.5 last:border-b-0 ${
        isDragging ? "bg-[#deebff] shadow-lg" : "bg-white"
      } ${
        // Hidden columns used to be sorted to the bottom to keep them out of
        // the way; that made rows teleport on toggle, so they stay in place
        // and are dimmed instead.
        column.hidden_default && !column.pinned && !column.required
          ? "opacity-55"
          : ""
      }`}
    >
      <div className="flex items-center gap-2">
        <button
          ref={setActivatorNodeRef}
          type="button"
          disabled={busy}
          aria-label={`Drag ${column.label}`}
          className="inline-flex h-8 w-8 cursor-grab items-center justify-center rounded border border-[#dfe1e6] bg-[#fafbfc] text-[#6b778c] hover:border-[#0c66e4] hover:text-[#0c66e4] active:cursor-grabbing disabled:cursor-not-allowed disabled:opacity-50"
          {...dragAttributes}
          {...listeners}
        >
          <GripVertical className="h-4 w-4" />
        </button>
        <span className="inline-flex h-7 min-w-7 items-center justify-center rounded-full bg-[#f1f2f4] px-2 text-xs font-bold text-[#44546f]">
          {index + 1}
        </span>
      </div>
      <input
        defaultValue={column.label}
        className="h-9 w-full rounded border border-transparent bg-transparent px-3 text-sm font-bold text-[#172b4d] outline-none transition hover:border-[#dfe1e6] hover:bg-white focus:border-[#0c66e4] focus:bg-white"
        onBlur={(event) => {
          const label = event.target.value.trim();
          if (label && label !== column.label) {
            void onPatch({ label });
          }
        }}
      />
      <span className="inline-flex w-fit rounded bg-[#f1f2f4] px-2.5 py-1 text-xs font-bold uppercase tracking-wide text-[#44546f]">
        {COLUMN_TYPE_LABEL[column.type]}
      </span>
      <ToggleSwitch
        checked={column.pinned}
        onChange={(next) =>
          void onPatch({
            pinned: next,
            ...(next ? { hidden_default: false } : {}),
          })
        }
      />
      <ToggleSwitch
        checked={column.required}
        disabled={isAutoGeneratedColumn(column)}
        title={requiredColumnTitle(column, scope)}
        onChange={(next) =>
          void onPatch({
            required: next,
            ...(next ? { hidden_default: false } : {}),
          })
        }
      />
      <ToggleSwitch
        checked={!column.pinned && !column.required && column.hidden_default}
        disabled={column.pinned || column.required}
        title={
          column.required
            ? "Required fields must always be reachable — turn off Required first."
            : undefined
        }
        onChange={(next) => void onPatch({ hidden_default: next })}
      />
      <ToggleSwitch
        checked={column.show_in_detail || column.required}
        disabled={column.is_system || column.required}
        title={
          column.is_system
            ? "Built-in fields always appear on the form unless Hidden — Detail only applies to custom columns."
            : column.required
              ? "Required fields must always be reachable — turn off Required first."
              : undefined
        }
        onChange={(next) => void onPatch({ show_in_detail: next })}
      />
      {column.is_system ? (
        <span className="text-xs font-bold uppercase text-[#97a0af]">System</span>
      ) : (
        <button
          type="button"
          disabled={busy || column.required}
          title={column.required ? "Turn off Required before archiving." : undefined}
          onClick={() => void onArchive()}
          className="inline-flex w-fit items-center gap-1 rounded px-2 py-1 text-sm font-bold text-[#bf2600] hover:bg-[#ffebe6] disabled:cursor-not-allowed disabled:opacity-50"
        >
          <Trash2 className="h-4 w-4" /> Archive
        </button>
      )}
    </div>
  );
}

function StaticColumnRow({
  column,
  scope,
  index,
  busy,
  onPatch,
  onArchive,
}: {
  column: TableColumn;
  scope: TableScope;
  index: number;
  busy: boolean;
  onPatch: (patch: Record<string, unknown>) => Promise<void>;
  onArchive: () => void;
}) {
  return (
    <div
      className={`grid grid-cols-[112px_minmax(240px,1fr)_120px_104px_104px_104px_112px_120px] items-center border-b border-[#ebecf0] bg-white px-4 py-2.5 last:border-b-0 ${
        column.hidden_default && !column.pinned && !column.required
          ? "opacity-55"
          : ""
      }`}
    >
      <div className="flex items-center gap-2">
        <span
          aria-hidden="true"
          className="inline-flex h-8 w-8 items-center justify-center rounded border border-[#dfe1e6] bg-[#fafbfc] text-[#6b778c]"
        >
          <GripVertical className="h-4 w-4" />
        </span>
        <span className="inline-flex h-7 min-w-7 items-center justify-center rounded-full bg-[#f1f2f4] px-2 text-xs font-bold text-[#44546f]">
          {index + 1}
        </span>
      </div>
      <input
        defaultValue={column.label}
        className="h-9 w-full rounded border border-transparent bg-transparent px-3 text-sm font-bold text-[#172b4d] outline-none transition hover:border-[#dfe1e6] hover:bg-white focus:border-[#0c66e4] focus:bg-white"
        onBlur={(event) => {
          const label = event.target.value.trim();
          if (label && label !== column.label) {
            void onPatch({ label });
          }
        }}
      />
      <span className="inline-flex w-fit rounded bg-[#f1f2f4] px-2.5 py-1 text-xs font-bold uppercase tracking-wide text-[#44546f]">
        {COLUMN_TYPE_LABEL[column.type]}
      </span>
      <ToggleSwitch
        checked={column.pinned}
        onChange={(next) =>
          void onPatch({
            pinned: next,
            ...(next ? { hidden_default: false } : {}),
          })
        }
      />
      <ToggleSwitch
        checked={column.required}
        disabled={isAutoGeneratedColumn(column)}
        title={requiredColumnTitle(column, scope)}
        onChange={(next) =>
          void onPatch({
            required: next,
            ...(next ? { hidden_default: false } : {}),
          })
        }
      />
      <ToggleSwitch
        checked={!column.pinned && !column.required && column.hidden_default}
        disabled={column.pinned || column.required}
        title={
          column.required
            ? "Required fields must always be reachable — turn off Required first."
            : undefined
        }
        onChange={(next) => void onPatch({ hidden_default: next })}
      />
      <ToggleSwitch
        checked={column.show_in_detail || column.required}
        disabled={column.is_system || column.required}
        title={
          column.is_system
            ? "Built-in fields always appear on the form unless Hidden — Detail only applies to custom columns."
            : column.required
              ? "Required fields must always be reachable — turn off Required first."
              : undefined
        }
        onChange={(next) => void onPatch({ show_in_detail: next })}
      />
      {column.is_system ? (
        <span className="text-xs font-bold uppercase text-[#97a0af]">System</span>
      ) : (
        <button
          type="button"
          disabled={busy || column.required}
          title={column.required ? "Turn off Required before archiving." : undefined}
          onClick={() => void onArchive()}
          className="inline-flex w-fit items-center gap-1 rounded px-2 py-1 text-sm font-bold text-[#bf2600] hover:bg-[#ffebe6] disabled:cursor-not-allowed disabled:opacity-50"
        >
          <Trash2 className="h-4 w-4" /> Archive
        </button>
      )}
    </div>
  );
}

type DropdownValueRow = {
  id: string;
  label: string;
  color: string | null;
  isTerminal?: boolean;
  treatAsTerminal?: boolean;
  triggersQc?: boolean;
};

type DropdownValueColorAppearance =
  | "category"
  | "enrollment-identity"
  | "enrollment-state";

function DropdownValueColorControl({
  label,
  identityKey,
  color,
  fallbackColor,
  appearance,
  recommended = false,
  disabled = false,
  onRecommendNext,
  onColorChange,
  onColorCommit,
}: {
  label: string;
  identityKey: string;
  color: string | null;
  fallbackColor: string;
  appearance: DropdownValueColorAppearance;
  recommended?: boolean;
  disabled?: boolean;
  onRecommendNext?: () => void;
  onColorChange?: (color: string) => void;
  onColorCommit?: (color: string) => void;
}) {
  const [draftColor, setDraftColor] = useState(color ?? fallbackColor);
  const [dirty, setDirty] = useState(false);
  const draftColorRef = useRef(color ?? fallbackColor);
  const dirtyRef = useRef(false);
  const controlled = Boolean(onColorChange);
  const displayedColor = controlled
    ? color ?? fallbackColor
    : dirty
      ? draftColor
      : color ?? fallbackColor;
  const previewColor = controlled ? color : dirty ? draftColor : color;
  const preview =
    appearance === "enrollment-state"
      ? enrollmentStateBadgeStyle({ color: previewColor })
      : appearance === "enrollment-identity"
        ? enrollmentIdentityBadgeStyle({ color: previewColor })
        : (() => {
          const palette = tableColumnOptionBadgePalette({
            id: identityKey,
            label: label || "Dropdown value",
            color: previewColor,
          });
          return { bg: palette.background, fg: palette.foreground };
        })();
  const previewLabel = label.trim() || (recommended ? "Recommended" : "Preview");

  return (
    <div className="flex h-10 min-w-0 items-center gap-2 rounded border border-[#dfe1e6] bg-white px-2">
      <span
        className="min-w-0 flex-1 truncate rounded px-2 py-1 text-[11px] font-semibold uppercase tracking-[0.025em]"
        style={{ backgroundColor: preview.bg, color: preview.fg }}
        title={`${previewLabel} — ${displayedColor}`}
      >
        {previewLabel}
      </span>
      {onRecommendNext ? (
        <button
          type="button"
          disabled={disabled}
          onClick={onRecommendNext}
          className={`inline-flex h-7 shrink-0 items-center gap-1 rounded px-1.5 text-[10px] font-bold uppercase transition hover:bg-[#e9f2ff] disabled:cursor-not-allowed disabled:opacity-50 ${
            recommended ? "bg-[#e9f2ff] text-[#0c66e4]" : "text-[#6b778c]"
          }`}
          title="Try another recommended color"
          aria-label="Try another recommended color"
        >
          <RefreshCw className="h-3 w-3" /> Auto
        </button>
      ) : null}
      <label
        className={`relative h-7 w-8 shrink-0 overflow-hidden rounded border border-[#c1c7d0] bg-white p-1 ${
          disabled ? "cursor-not-allowed opacity-50" : "cursor-pointer"
        }`}
        title="Choose a different base color"
      >
        <span
          className="block h-full w-full rounded-sm"
          style={{ backgroundColor: displayedColor }}
        />
        <input
          type="color"
          value={displayedColor}
          disabled={disabled}
          aria-label={`Color for ${label || "new dropdown value"}`}
          onChange={(event) => {
            const nextColor = event.target.value;
            draftColorRef.current = nextColor;
            dirtyRef.current = true;
            setDraftColor(nextColor);
            setDirty(true);
            onColorChange?.(nextColor);
          }}
          onBlur={() => {
            if (!dirtyRef.current) return;
            dirtyRef.current = false;
            onColorCommit?.(draftColorRef.current);
          }}
          className="absolute inset-0 h-full w-full cursor-pointer opacity-0 disabled:cursor-not-allowed"
        />
      </label>
    </div>
  );
}

type DropdownValueGroup =
  | { kind: "category"; key: string; navLabel: string; count: number }
  | { kind: "custom"; key: string; navLabel: string; count: number; columnId: string }
  | {
      kind: "optionSet";
      key: string;
      navLabel: string;
      count: number;
      setKey: EnrollmentOptionSetKey;
    };

// Mọi "dropdown value" của app — custom column, CS Category, Enrollment Option
// Set — chuẩn hoá về 1 màn hình duy nhất: nav trái chọn nhóm, chi tiết phải
// thêm/sửa/archive. Field đặc thù (Terminal/QC chỉ "stage") hiện có điều kiện
// theo nhóm đang chọn. Usage được kiểm tra chỉ sau khi admin bấm Archive.
function ConfigDropdownValuesSection({
  scope,
  columns,
  options,
  categories,
  optionSets,
  optionsBySet,
  busy,
  available,
  availabilityError,
  categoriesAvailable,
  categoriesError,
  run,
  refreshScope,
  onCategoriesChange,
  onOptionDataChange,
}: {
  scope: TableScope;
  columns: TableColumn[];
  options: TableColumnOption[];
  categories: TaskCategory[];
  optionSets: EnrollmentOptionSet[];
  optionsBySet: EnrollmentOptionsBySet;
  busy: boolean;
  available: boolean;
  availabilityError?: string;
  categoriesAvailable: boolean;
  categoriesError?: string;
  run: (action: () => Promise<unknown>, success: string) => Promise<void>;
  refreshScope: (scope?: TableScope) => Promise<void>;
  onCategoriesChange: Dispatch<SetStateAction<TaskCategory[]>>;
  onOptionDataChange: () => Promise<void>;
}) {
  const [refreshError, setRefreshError] = useState<string | null>(null);
  const categoryRefreshSequenceRef = useRef(0);
  const isEnrollmentScope = scope === "aca" || scope === "medicare";
  // KHÔNG nhận Status/Priority (CS) — cũng is_system+dropdown nhưng giá trị
  // hardcode trong TASK_STATUSES/TASK_PRIORITIES (TS enum), không có bảng để sửa.
  const customDropdownColumns = columns.filter((column) => column.type === "dropdown" && !column.is_system);
  const hasCategory = scope === "cs" && columns.some((column) => column.is_system && column.key === "category");

  const groups: DropdownValueGroup[] = [
    ...(isEnrollmentScope
      ? optionSets.map((set) => ({
          kind: "optionSet" as const,
          key: `set:${set.key}`,
          navLabel: set.label,
          count: (optionsBySet[set.key] ?? []).filter((o) => !o.archived_at).length,
          setKey: set.key,
        }))
      : []),
    ...(hasCategory
      ? [{ kind: "category" as const, key: "category", navLabel: "Category", count: categories.length }]
      : []),
    ...customDropdownColumns.map((column) => ({
      kind: "custom" as const,
      key: `col:${column.id}`,
      navLabel: column.label,
      count: options.filter((o) => o.column_id === column.id && !o.archived_at).length,
      columnId: column.id,
    })),
  ];

  const [selectedKey, setSelectedKey] = useState(groups[0]?.key ?? "");
  const selected = groups.find((g) => g.key === selectedKey) ?? groups[0];
  const categoryUnavailable = selected?.kind === "category" && !categoriesAvailable;
  const controlsDisabled = busy || !available || Boolean(refreshError) || categoryUnavailable;
  const sectionError = refreshError ?? (categoryUnavailable ? categoriesError : availabilityError);
  const isStageGroup = selected?.kind === "optionSet" && selected.setKey === "stage";
  // Dashboard-terminal semantics belong only to the ACA Overview. They are
  // not a shared CS/Medicare workflow rule.
  const isAcaStageGroup = scope === "aca" && isStageGroup;
  const isConsentGroup = selected?.kind === "optionSet" && selected.setKey === "consent";
  const protectsLabelIdentity =
    selected?.kind === "optionSet" && (selected.setKey === "stage" || selected.setKey === "consent");

  const [label, setLabel] = useState("");
  const [color, setColor] = useState("");
  const [usesRecommendedColor, setUsesRecommendedColor] = useState(true);
  const [isTerminal, setIsTerminal] = useState(false);
  const [treatAsTerminal, setTreatAsTerminal] = useState(false);
  const [triggersQc, setTriggersQc] = useState(false);
  const [confirmArchiveId, setConfirmArchiveId] = useState<string | null>(null);
  const [archiveUsage, setArchiveUsage] = useState<{ id: string; count: number } | null>(null);
  const [pendingStageRuleIds, setPendingStageRuleIds] = useState<Set<string>>(new Set());
  const stageRuleQueuesRef = useRef(new Map<string, Promise<void>>());
  const pendingStageRuleCountsRef = useRef(new Map<string, number>());

  const valueRows: DropdownValueRow[] = !selected
    ? []
    : selected.kind === "category"
      ? categories.map((c) => ({ id: c.id, label: c.name, color: c.color }))
      : selected.kind === "custom"
        ? options
            .filter((o) => o.column_id === selected.columnId)
            .map((o) => ({ id: o.id, label: o.label, color: o.color }))
        : sortEnrollmentOptionsByLabel(optionsBySet[selected.setKey] ?? []).map((o) => ({
            id: o.id,
            label: o.label,
            color: o.color,
            isTerminal: o.is_terminal,
            treatAsTerminal: o.treat_as_terminal,
            triggersQc: o.triggers_qc,
          }));
  const activeConsentCount = isConsentGroup ? valueRows.length : 0;
  const recommendedColor = recommendDropdownValueColor(
    valueRows.map((row) => row.color)
  );
  const draftColor = color || recommendedColor;
  const colorAppearance: DropdownValueColorAppearance =
    selected?.kind === "optionSet"
      ? selected.setKey === "stage"
        ? "enrollment-state"
        : "enrollment-identity"
      : "category";

  async function refreshCategories() {
    const requestSequence = categoryRefreshSequenceRef.current + 1;
    categoryRefreshSequenceRef.current = requestSequence;
    try {
      const response = await fetch("/api/tasks/categories", { cache: "no-store" });
      const payload = await readRefreshResponse<unknown>(
        response,
        "Could not refresh task categories."
      );
      if (!isLatestRefresh(requestSequence, categoryRefreshSequenceRef.current)) return;
      if (!payload || typeof payload !== "object" || !Array.isArray((payload as { categories?: unknown }).categories)) {
        throw new Error("Could not refresh task categories.");
      }
      onCategoriesChange((payload as { categories: TaskCategory[] }).categories);
      setRefreshError(null);
    } catch (error) {
      if (!isLatestRefresh(requestSequence, categoryRefreshSequenceRef.current)) return;
      setRefreshError(error instanceof Error ? error.message : "Could not refresh task categories.");
      throw error;
    }
  }

  async function addValue() {
    if (!selected || controlsDisabled) return;
    if (selected.kind === "category") {
      await requestJson("/api/tasks/categories", {
        method: "POST",
        body: JSON.stringify({ name: label, color: draftColor }),
      });
      await refreshCategories();
    } else if (selected.kind === "custom") {
      await requestJson(`/api/config/columns/${selected.columnId}/options`, {
        method: "POST",
        body: JSON.stringify({ label, color: draftColor }),
      });
      await refreshScope(scope);
    } else {
      await requestJson("/api/enrollment/option-sets", {
        method: "POST",
        body: JSON.stringify({
          program: scope,
          set_key: selected.setKey,
          label,
          color: draftColor,
          is_terminal: isTerminal,
          // This flag has meaning only for the ACA Overview. The UI hides it
          // outside ACA, and the guard here prevents stale form state from
          // leaking it into a Medicare option after switching scopes.
          treat_as_terminal: isAcaStageGroup && treatAsTerminal,
          triggers_qc: triggersQc,
        }),
      });
      await onOptionDataChange();
    }
  }

  async function renameValue(id: string, nextLabel: string) {
    if (!selected || controlsDisabled) return;
    if (selected.kind === "category") {
      await requestJson(`/api/tasks/categories/${id}`, { method: "PATCH", body: JSON.stringify({ name: nextLabel }) });
      await refreshCategories();
    } else if (selected.kind === "custom") {
      await requestJson(`/api/config/columns/${selected.columnId}/options/${id}`, {
        method: "PATCH",
        body: JSON.stringify({ label: nextLabel }),
      });
      await refreshScope(scope);
    } else {
      await requestJson(`/api/enrollment/option-sets/${id}`, { method: "PATCH", body: JSON.stringify({ label: nextLabel }) });
      await onOptionDataChange();
    }
  }

  async function recolorValue(id: string, nextColor: string) {
    if (!selected || controlsDisabled) return;
    if (selected.kind === "category") {
      await requestJson(`/api/tasks/categories/${id}`, { method: "PATCH", body: JSON.stringify({ color: nextColor }) });
      await refreshCategories();
    } else if (selected.kind === "custom") {
      await requestJson(`/api/config/columns/${selected.columnId}/options/${id}`, {
        method: "PATCH",
        body: JSON.stringify({ color: nextColor }),
      });
      await refreshScope(scope);
    } else {
      await requestJson(`/api/enrollment/option-sets/${id}`, { method: "PATCH", body: JSON.stringify({ color: nextColor }) });
      await onOptionDataChange();
    }
  }

  async function toggleStageRule(id: string, patch: { is_terminal?: boolean; treat_as_terminal?: boolean; triggers_qc?: boolean }) {
    if (controlsDisabled) return;
    const pendingCount = (pendingStageRuleCountsRef.current.get(id) ?? 0) + 1;
    pendingStageRuleCountsRef.current.set(id, pendingCount);
    setPendingStageRuleIds((current) => new Set(current).add(id));

    const previous = stageRuleQueuesRef.current.get(id) ?? Promise.resolve();
    const operation = previous
      .catch(() => undefined)
      .then(async () => {
        await requestJson(`/api/enrollment/option-sets/${id}`, {
          method: "PATCH",
          body: JSON.stringify(patch),
        });
        await onOptionDataChange();
      });
    stageRuleQueuesRef.current.set(id, operation);
    try {
      await operation;
    } finally {
      const remaining = (pendingStageRuleCountsRef.current.get(id) ?? 1) - 1;
      if (remaining > 0) {
        pendingStageRuleCountsRef.current.set(id, remaining);
      } else {
        pendingStageRuleCountsRef.current.delete(id);
        setPendingStageRuleIds((current) => {
          const next = new Set(current);
          next.delete(id);
          return next;
        });
      }
      if (stageRuleQueuesRef.current.get(id) === operation) {
        stageRuleQueuesRef.current.delete(id);
      }
    }
  }

  async function archiveValue(id: string) {
    if (!selected || controlsDisabled) return;
    if (selected.kind === "category") {
      await requestJson(`/api/tasks/categories/${id}`, { method: "DELETE" });
      await refreshCategories();
    } else if (selected.kind === "custom") {
      await requestJson(`/api/config/columns/${selected.columnId}/options/${id}`, { method: "DELETE" });
      await refreshScope(scope);
    } else {
      await requestJson(`/api/enrollment/option-sets/${id}`, { method: "DELETE" });
      await onOptionDataChange();
    }
  }

  async function prepareArchive(id: string) {
    if (!selected || controlsDisabled) return;
    const selectedSnapshot = selected;
    setArchiveUsage(null);
    if (selectedSnapshot.kind === "category") {
      setConfirmArchiveId(id);
      return;
    }

    const usageUrl = selectedSnapshot.kind === "custom"
      ? `/api/config/columns/${selectedSnapshot.columnId}/options/${id}/usage`
      : `/api/enrollment/option-sets/${id}/usage`;
    const payload = await requestJson(usageUrl, { cache: "no-store" });
    const usageCount = Number(payload?.usage_count);
    if (!Number.isSafeInteger(usageCount) || usageCount < 0) {
      throw new Error("Could not check option usage.");
    }
    // Do not open a confirmation for a different group if the admin changed
    // scope/group while the on-demand request was in flight.
    if (selectedKey !== selectedSnapshot.key) return;
    setArchiveUsage({ id, count: usageCount });
    setConfirmArchiveId(id);
  }

  const confirmRow = valueRows.find((r) => r.id === confirmArchiveId) ?? null;
  const wouldDropConsentBelowTwo = isConsentGroup && activeConsentCount <= 2;

  function resetValueDraft() {
    setLabel("");
    setColor("");
    setUsesRecommendedColor(true);
    setIsTerminal(false);
    setTreatAsTerminal(false);
    setTriggersQc(false);
    setConfirmArchiveId(null);
    setArchiveUsage(null);
  }

  return (
    <section className="overflow-hidden rounded border border-[#dfe1e6] bg-white shadow-sm">
      <div className="border-b border-[#dfe1e6] px-6 py-4">
        <h2 className="text-lg font-bold">Dropdown values</h2>
        <p className="mt-1 text-sm text-[#6b778c]">
          Every dropdown value — custom columns, Category, and Enrollment option
          sets — is managed here in one place.
        </p>
      </div>
      {!available || refreshError || categoryUnavailable ? (
        <ConfigSectionUnavailable message={sectionError} />
      ) : null}
      {groups.length === 0 ? (
        <div className="px-6 py-10 text-sm font-semibold text-[#6b778c]">No dropdown values yet.</div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-[200px_minmax(0,1fr)]">
          <nav className="border-b border-[#dfe1e6] bg-[#f7f8fa] p-3 md:border-b-0 md:border-r">
            {groups.map((group) => (
              <button
                key={group.key}
                type="button"
                onClick={() => {
                  setSelectedKey(group.key);
                  resetValueDraft();
                }}
                className={`mb-1 flex w-full items-center justify-between rounded px-3 py-2 text-left text-sm font-bold transition ${
                  group.key === selected?.key ? "bg-[#e9f2ff] text-[#0c66e4]" : "text-[#42526e] hover:bg-white"
                }`}
              >
                {group.navLabel}
                <span>{group.count}</span>
              </button>
            ))}
          </nav>
          <div className="min-w-0 p-4">
            <form
              className={`grid grid-cols-1 gap-2 border-b border-[#dfe1e6] pb-4 ${
                isAcaStageGroup
                  ? "md:grid-cols-[minmax(0,1fr)_240px_110px_110px_110px_auto]"
                  : isStageGroup
                    ? "md:grid-cols-[minmax(0,1fr)_240px_110px_110px_auto]"
                    : "md:grid-cols-[minmax(0,1fr)_240px_auto]"
              }`}
              onSubmit={(event) => {
                event.preventDefault();
                if (!selected || !label.trim()) return;
                void run(async () => {
                  await addValue();
                  setLabel("");
                  setColor("");
                  setUsesRecommendedColor(true);
                  setIsTerminal(false);
                  setTreatAsTerminal(false);
                  setTriggersQc(false);
                }, "Option added.");
              }}
            >
              <input
                value={label}
                onChange={(event) => setLabel(event.target.value)}
                placeholder={`New ${selected?.navLabel ?? "value"}`}
                className="h-10 rounded border border-[#dfe1e6] px-3 text-sm font-semibold outline-none focus:border-[#0c66e4]"
              />
              <DropdownValueColorControl
                label={label}
                identityKey={`draft:${selected?.key ?? "value"}`}
                color={draftColor}
                fallbackColor={recommendedColor}
                appearance={colorAppearance}
                recommended={usesRecommendedColor}
                disabled={controlsDisabled}
                onRecommendNext={() => {
                  setColor(
                    nextRecommendedDropdownValueColor(
                      draftColor,
                      valueRows.map((row) => row.color)
                    )
                  );
                  setUsesRecommendedColor(true);
                }}
                onColorChange={(nextColor) => {
                  setColor(nextColor);
                  setUsesRecommendedColor(false);
                }}
              />
              {isStageGroup ? (
                <>
                  <label
                    className="flex items-center justify-center gap-2 rounded border border-[#dfe1e6] px-2 text-xs font-bold text-[#42526e]"
                    title="Workflow terminal: entering this stage closes the enrollment record."
                  >
                    <input
                      type="checkbox"
                      disabled={controlsDisabled}
                      checked={isTerminal}
                      onChange={(event) => setIsTerminal(event.target.checked)}
                    />
                    Workflow terminal
                  </label>
                  <label className="flex items-center justify-center gap-2 rounded border border-[#dfe1e6] px-2 text-xs font-bold text-[#42526e]">
                    <input
                      type="checkbox"
                      disabled={controlsDisabled}
                      checked={triggersQc}
                      onChange={(event) => setTriggersQc(event.target.checked)}
                    />
                    QC
                  </label>
                </>
              ) : null}
              {isAcaStageGroup ? (
                <label
                  className="flex items-center justify-center gap-2 rounded border border-[#dfe1e6] px-2 text-xs font-bold text-[#42526e]"
                  title="ACA overview only: excludes this stage from active-work metrics; does not close the enrollment record."
                >
                  <input
                    type="checkbox"
                    disabled={controlsDisabled}
                    checked={treatAsTerminal}
                    onChange={(event) => setTreatAsTerminal(event.target.checked)}
                  />
                  Dashboard terminal (ACA only)
                </label>
              ) : null}
              <button
                type="submit"
                disabled={controlsDisabled || !label.trim() || (isConsentGroup && activeConsentCount >= 2)}
                title={
                  isConsentGroup && activeConsentCount >= 2
                    ? "Consent supports exactly 2 active options (Yes / other)."
                    : undefined
                }
                className="inline-flex h-10 items-center justify-center gap-2 rounded bg-[#0c66e4] px-4 text-sm font-bold text-white disabled:opacity-40"
              >
                <Plus className="h-4 w-4" /> Add
              </button>
            </form>
            <div className="mt-4 min-w-0 overflow-hidden rounded-lg border border-[#dfe1e6]">
              <table className="w-full table-fixed border-collapse text-sm">
                <colgroup>
                  <col className={isStageGroup ? "w-[28%]" : "w-[40%]"} />
                  <col className={isStageGroup ? "w-[32%]" : "w-[45%]"} />
                  {isStageGroup ? <col className="w-[28%]" /> : null}
                  <col className={isStageGroup ? "w-[12%]" : "w-[15%]"} />
                </colgroup>
                <thead className="bg-[#f7f8fa] text-xs font-bold uppercase text-[#6b778c]">
                  <tr>
                    <th className="border-b border-r border-[#dfe1e6] px-3 py-2 text-left">Label</th>
                    <th className="border-b border-r border-[#dfe1e6] px-3 py-2 text-left">Color</th>
                    {isStageGroup ? (
                      <th className="border-b border-r border-[#dfe1e6] px-3 py-2 text-left">Rules</th>
                    ) : null}
                    <th className="border-b border-[#dfe1e6] px-3 py-2 text-right">Action</th>
                  </tr>
                </thead>
                <tbody>
                  {valueRows.map((row) => {
                    const disableArchive = isConsentGroup && wouldDropConsentBelowTwo;
                    return (
                      <tr key={row.id}>
                        <td className="border-b border-r border-[#dfe1e6] px-3 py-2">
                          <input
                            defaultValue={row.label}
                            disabled={controlsDisabled || protectsLabelIdentity}
                            title={
                              protectsLabelIdentity
                                ? "Stage and Consent labels are protected workflow identities."
                                : undefined
                            }
                            onBlur={(event) => {
                              if (protectsLabelIdentity) return;
                              const value = event.target.value.trim();
                              if (value && value !== row.label) void run(() => renameValue(row.id, value), "Option updated.");
                            }}
                            className="h-8 w-full rounded border border-[#dfe1e6] px-2 font-semibold outline-none focus:border-[#0c66e4] disabled:cursor-not-allowed disabled:bg-[#f7f8fa] disabled:text-[#6b778c]"
                          />
                        </td>
                        <td className="border-b border-r border-[#dfe1e6] px-3 py-2">
                          <DropdownValueColorControl
                            key={`color:${row.id}:${row.color ?? "none"}`}
                            label={row.label}
                            identityKey={row.id}
                            color={row.color}
                            fallbackColor={recommendedColor}
                            appearance={colorAppearance}
                            disabled={controlsDisabled}
                            onColorCommit={(nextColor) =>
                              void run(
                                () => recolorValue(row.id, nextColor),
                                "Option updated."
                              )
                            }
                          />
                        </td>
                        {isStageGroup ? (
                          <td className="border-b border-r border-[#dfe1e6] px-3 py-2 text-xs font-semibold text-[#42526e]">
                            <div className="flex flex-wrap gap-2">
                              <label className="flex items-center gap-1.5" title="Workflow terminal: entering this stage closes the enrollment record.">
                                <input
                                  type="checkbox"
                                  disabled={controlsDisabled || pendingStageRuleIds.has(row.id)}
                                  checked={Boolean(row.isTerminal)}
                                  onChange={(event) =>
                                    void run(
                                      () => toggleStageRule(row.id, { is_terminal: event.target.checked }),
                                      "Option updated."
                                    )
                                  }
                                />
                                Workflow terminal
                              </label>
                              {isAcaStageGroup ? (
                                <label className="flex items-center gap-1.5" title="ACA overview only: excludes this stage from active-work metrics; does not close the enrollment record.">
                                  <input
                                    type="checkbox"
                                    disabled={controlsDisabled || pendingStageRuleIds.has(row.id)}
                                    checked={Boolean(row.treatAsTerminal)}
                                    onChange={(event) =>
                                      void run(
                                        () => toggleStageRule(row.id, { treat_as_terminal: event.target.checked }),
                                        "Option updated."
                                      )
                                    }
                                  />
                                  Dashboard terminal (ACA only)
                                </label>
                              ) : null}
                              <label className="flex items-center gap-1.5">
                                <input
                                  type="checkbox"
                                  disabled={controlsDisabled || pendingStageRuleIds.has(row.id)}
                                  checked={Boolean(row.triggersQc)}
                                  onChange={(event) =>
                                    void run(
                                      () => toggleStageRule(row.id, { triggers_qc: event.target.checked }),
                                      "Option updated."
                                    )
                                  }
                                />
                                QC
                              </label>
                            </div>
                          </td>
                        ) : null}
                        <td className="border-b border-[#dfe1e6] px-3 py-2 text-right">
                          <button
                            type="button"
                            disabled={controlsDisabled || disableArchive}
                            title={disableArchive ? "Consent needs at least 2 active options." : undefined}
                            onClick={() => void run(
                              () => prepareArchive(row.id),
                              "Archive confirmation ready."
                            )}
                            className="text-xs font-bold text-[#bf2600] hover:underline disabled:opacity-40 disabled:no-underline"
                          >
                            Archive
                          </button>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}
      {confirmRow ? (
        <ConfirmDialog
          title={`Archive "${confirmRow.label}"?`}
          description={
            selected?.kind === "optionSet" || selected?.kind === "custom"
              ? archiveUsage?.id === confirmRow.id
                ? archiveUsage.count > 0
                  ? `${archiveUsage.count} record(s) currently use this option. Archiving removes it from pickers going forward — those records keep showing it, but nobody can select it for a new record until it's restored.`
                  : "No live records currently use this option. It will be removed from pickers going forward."
                : "Usage could not be verified. Close this dialog and retry before archiving."
              : "This value will be removed from pickers going forward. Existing records that reference it keep showing it."
          }
          confirmLabel="Archive"
          busy={busy}
          onCancel={() => {
            setConfirmArchiveId(null);
            setArchiveUsage(null);
          }}
          onConfirm={() => {
            const id = confirmRow.id;
            setConfirmArchiveId(null);
            setArchiveUsage(null);
            void run(() => archiveValue(id), "Option archived.");
          }}
        />
      ) : null}
    </section>
  );
}

function ConfirmDialog({
  title,
  description,
  confirmLabel,
  busy = false,
  onCancel,
  onConfirm,
}: {
  title: string;
  description: string;
  confirmLabel: string;
  busy?: boolean;
  onCancel: () => void;
  onConfirm: () => void | Promise<void>;
}) {
  const dialogRef = useRef<HTMLDivElement>(null);
  const cancelRef = useRef<HTMLButtonElement>(null);
  const cancelHandlerRef = useRef(onCancel);
  const submittingRef = useRef(false);
  const [submitting, setSubmitting] = useState(false);
  const titleId = useId();
  const descriptionId = useId();

  useEffect(() => {
    cancelHandlerRef.current = onCancel;
  }, [onCancel]);

  useEffect(() => {
    const previousFocus = document.activeElement as HTMLElement | null;
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    cancelRef.current?.focus();

    function onKeyDown(event: KeyboardEvent) {
      if (event.key === "Escape") {
        event.preventDefault();
        if (!submittingRef.current) cancelHandlerRef.current();
        return;
      }
      if (event.key !== "Tab" || !dialogRef.current) return;
      const focusable = Array.from(
        dialogRef.current.querySelectorAll<HTMLElement>(
          'button:not([disabled]), [href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])'
        )
      );
      if (focusable.length === 0) return;
      const first = focusable[0];
      const last = focusable[focusable.length - 1];
      if (event.shiftKey && document.activeElement === first) {
        event.preventDefault();
        last.focus();
      } else if (!event.shiftKey && document.activeElement === last) {
        event.preventDefault();
        first.focus();
      }
    }

    document.addEventListener("keydown", onKeyDown);
    return () => {
      document.removeEventListener("keydown", onKeyDown);
      document.body.style.overflow = previousOverflow;
      previousFocus?.focus();
    };
  }, []);

  function handleConfirm() {
    if (busy || submitting) return;
    submittingRef.current = true;
    setSubmitting(true);
    void onConfirm();
  }

  return (
    <div
      className="fixed inset-0 z-[90] flex items-center justify-center bg-[#091e42]/50 p-4"
      role="presentation"
      onMouseDown={(event) => {
        if (event.target === event.currentTarget && !busy && !submitting) onCancel();
      }}
    >
      <div
        ref={dialogRef}
        role="dialog"
        aria-modal="true"
        aria-labelledby={titleId}
        aria-describedby={descriptionId}
        className="w-full max-w-sm rounded-lg bg-white p-5 shadow-2xl"
      >
        <h2 id={titleId} className="text-lg font-bold text-[#172b4d]">{title}</h2>
        <p id={descriptionId} className="mt-2 text-sm leading-6 text-[#5e6c84]">{description}</p>
        <div className="mt-5 flex justify-end gap-2">
          <button
            type="button"
            ref={cancelRef}
            onClick={onCancel}
            disabled={busy || submitting}
            className="rounded px-3 py-2 text-sm font-bold text-[#42526e] transition hover:bg-[#f4f5f7]"
          >
            Cancel
          </button>
          <button
            type="button"
            onClick={handleConfirm}
            disabled={busy || submitting}
            className="rounded bg-[#ca3521] px-3 py-2 text-sm font-bold text-white shadow-sm transition hover:bg-[#ae2a19] disabled:cursor-not-allowed disabled:opacity-60"
          >
            {busy || submitting ? "Working…" : confirmLabel}
          </button>
        </div>
      </div>
    </div>
  );
}

function ConfigAssistantSection({
  agents,
  candidates,
  assignees,
  members,
  busy,
  available,
  availabilityError,
  run,
  setMembers,
  onAgentsChange,
}: {
  agents: TaskAgent[];
  candidates: TaskAssignee[];
  assignees: TaskAssignee[];
  members: AssistantMember[];
  busy: boolean;
  available: boolean;
  availabilityError?: string;
  run: (action: () => Promise<unknown>, success: string) => Promise<void>;
  setMembers: Dispatch<SetStateAction<AssistantMember[]>>;
  onAgentsChange: Dispatch<SetStateAction<TaskAgent[]>>;
}) {
  const [agentEmail, setAgentEmail] = useState(agents[0]?.email ?? "");
  const [assistantEmail, setAssistantEmail] = useState("");
  const [newAgentEmail, setNewAgentEmail] = useState("");
  const [agentsRefreshError, setAgentsRefreshError] = useState<string | null>(null);
  const [membersRefreshError, setMembersRefreshError] = useState<string | null>(null);
  const agentsRefreshSequenceRef = useRef(0);
  const membersRefreshSequenceRef = useRef(0);
  const agentsControlsDisabled = busy || !available || Boolean(agentsRefreshError);
  const membersControlsDisabled =
    busy || !available || Boolean(agentsRefreshError) || Boolean(membersRefreshError);
  const agentEmails = new Set(agents.map((a) => a.email));
  // Agent picker: MỌI account active (khớp AgentGroupsModal cũ) — Agent không
  // bắt buộc có quyền task.work, họ có thể chưa từng dùng CS board.
  const agentCandidateOptions: SelectOption<string>[] = [
    { value: "", label: "Select person" },
    ...candidates
      .filter((person) => !agentEmails.has(person.email))
      .map((person) => ({ value: person.email, label: person.name?.trim() || person.email })),
  ];

  async function refreshAgents() {
    if (!available) return;
    const requestSequence = agentsRefreshSequenceRef.current + 1;
    agentsRefreshSequenceRef.current = requestSequence;
    try {
      const response = await fetch("/api/config/agents", { cache: "no-store" });
      const payload = await readRefreshResponse<unknown>(response, "Could not refresh agents.");
      if (!isLatestRefresh(requestSequence, agentsRefreshSequenceRef.current)) return;
      if (!payload || typeof payload !== "object" || !Array.isArray((payload as { agents?: unknown }).agents)) {
        throw new Error("Could not refresh agents.");
      }
      onAgentsChange((payload as { agents: TaskAgent[] }).agents);
      setAgentsRefreshError(null);
    } catch (error) {
      if (!isLatestRefresh(requestSequence, agentsRefreshSequenceRef.current)) return;
      setAgentsRefreshError(error instanceof Error ? error.message : "Could not refresh agents.");
      throw error;
    }
  }

  // Gộp cả 2 nguồn để label luôn resolve được tên — member.agent_email có thể
  // thuộc `candidates` (mọi account), member.cs_email chỉ thuộc `assignees`
  // (task-work roster). labelForEmail() fallback về raw email nếu không thấy.
  const candidateByEmail = useMemo(
    () => new Map([...candidates, ...assignees].map((person) => [person.email, person])),
    [candidates, assignees]
  );
  const agentOptions: SelectOption<string>[] = agents.map((agent) => ({
    value: agent.email,
    label: agent.name?.trim() || agent.email,
  }));
  // Assistant picker: CHỈ người có task.work/task.manage (khớp AgentGroupsModal
  // cũ, prop `cs`) — làm Assistant = được cấp quyền ngang agent-owner trên task
  // của agent đó, người không có quyền task.work không vào được /tasks nên
  // gán họ làm Assistant là vô nghĩa.
  const existingAssistantEmails = new Set(
    members
      .filter((member) => member.agent_email === agentEmail && member.is_assistant)
      .map((member) => member.cs_email)
  );
  const assistantOptions: SelectOption<string>[] = [
    { value: "", label: "Select assistant" },
    ...assignees.filter(
      (person) => person.email !== agentEmail && !existingAssistantEmails.has(person.email)
    ).map((person) => ({
      value: person.email,
      label: person.name?.trim() || person.email,
    })),
  ];
  // Hiện TẤT CẢ quan hệ agent→assistant, sắp theo tên agent rồi tên assistant
  // — dropdown "Agent" bên trên chỉ dùng để tạo mới, không lọc list này, để
  // admin xem được toàn bộ cấu trúc team trong 1 lần nhìn.
  const memberRows = [...members].sort((a, b) => {
    const agentCompare = labelForEmail(a.agent_email, candidateByEmail).localeCompare(
      labelForEmail(b.agent_email, candidateByEmail)
    );
    if (agentCompare !== 0) return agentCompare;
    return labelForEmail(a.cs_email, candidateByEmail).localeCompare(
      labelForEmail(b.cs_email, candidateByEmail)
    );
  });

  async function refreshMembers() {
    if (!available) return;
    const requestSequence = membersRefreshSequenceRef.current + 1;
    membersRefreshSequenceRef.current = requestSequence;
    try {
      const response = await fetch("/api/config/assistants", { cache: "no-store" });
      const payload = await readRefreshResponse<unknown>(
        response,
        "Could not refresh assistant memberships."
      );
      if (!isLatestRefresh(requestSequence, membersRefreshSequenceRef.current)) return;
      if (!payload || typeof payload !== "object" || !Array.isArray((payload as { members?: unknown }).members)) {
        throw new Error("Could not refresh assistant memberships.");
      }
      setMembers((payload as { members: AssistantMember[] }).members);
      setMembersRefreshError(null);
    } catch (error) {
      if (!isLatestRefresh(requestSequence, membersRefreshSequenceRef.current)) return;
      setMembersRefreshError(
        error instanceof Error ? error.message : "Could not refresh assistant memberships."
      );
      throw error;
    }
  }

  return (
    <>
      <section className="overflow-hidden rounded border border-[#dfe1e6] bg-white shadow-sm">
        <div className="border-b border-[#dfe1e6] px-6 py-4">
          <h2 className="text-lg font-bold">Agents</h2>
          <p className="mt-1 text-sm text-[#6b778c]">
            Add people as Agents. Removing an agent also unlinks all of their assistants.
          </p>
        </div>
        {!available || agentsRefreshError ? (
          <ConfigSectionUnavailable message={agentsRefreshError ?? availabilityError} />
        ) : null}
        <form
          className="grid gap-3 border-b border-[#dfe1e6] bg-[#fafbfc] p-4 md:grid-cols-[1fr_120px]"
          onSubmit={(event) => {
            event.preventDefault();
            if (!newAgentEmail) return;
            void run(async () => {
              await requestJson("/api/config/agents", {
                method: "POST",
                body: JSON.stringify({ email: newAgentEmail }),
              });
              setNewAgentEmail("");
              await refreshAgents();
            }, "Agent added.");
          }}
        >
          <DropdownSelect
            label="Person"
            value={newAgentEmail}
            options={agentCandidateOptions}
            onChange={setNewAgentEmail}
            placeholder="Select person"
          />
          <button
            type="submit"
            disabled={agentsControlsDisabled || !newAgentEmail}
            className="inline-flex h-10 items-center justify-center gap-2 rounded bg-[#0c66e4] px-4 text-sm font-bold text-white disabled:opacity-50"
          >
            <Plus className="h-4 w-4" /> Add
          </button>
        </form>
        {agents.map((agent) => (
          <div
            key={agent.email}
            className="grid grid-cols-[1fr_140px] items-center border-b border-[#ebecf0] px-4 py-2 last:border-b-0"
          >
            <div>
              <p className="text-sm font-bold">{agent.name?.trim() || agent.email}</p>
              <p className="text-xs font-semibold text-[#6b778c]">{agent.email}</p>
            </div>
            <button
              type="button"
              disabled={agentsControlsDisabled}
              onClick={() =>
                void run(async () => {
                  await requestJson("/api/config/agents", {
                    method: "DELETE",
                    body: JSON.stringify({ email: agent.email }),
                  });
                  await refreshAgents();
                  // Xoá agent cascade-xoá agent_members ở server — refresh
                  // luôn danh sách assistant để không còn row mồ côi trên UI.
                  await refreshMembers();
                }, "Agent removed.")
              }
              className="inline-flex w-fit items-center gap-1 rounded px-2 py-1 text-sm font-bold text-[#bf2600] hover:bg-[#ffebe6]"
            >
              <Trash2 className="h-4 w-4" /> Remove
            </button>
          </div>
        ))}
      </section>

      <section className="overflow-hidden rounded border border-[#dfe1e6] bg-white shadow-sm">
        <div className="border-b border-[#dfe1e6] px-6 py-4">
          <h2 className="text-lg font-bold">Assistant membership</h2>
          <p className="mt-1 text-sm text-[#6b778c]">
            Link an existing Agent to the people who assist them.
          </p>
        </div>
        {!available || agentsRefreshError || membersRefreshError ? (
          <ConfigSectionUnavailable
            message={agentsRefreshError ?? membersRefreshError ?? availabilityError}
          />
        ) : null}
        <form
          className="grid gap-3 border-b border-[#dfe1e6] bg-[#fafbfc] p-4 md:grid-cols-[280px_1fr_120px]"
          onSubmit={(event) => {
            event.preventDefault();
            void run(async () => {
              await requestJson("/api/config/assistants", {
                method: "POST",
                body: JSON.stringify({ agent_email: agentEmail, cs_email: assistantEmail }),
              });
              setAssistantEmail("");
              await refreshMembers();
            }, "Assistant added.");
          }}
        >
          <DropdownSelect
          label="Agent"
          value={agentEmail}
          options={agentOptions}
          onChange={setAgentEmail}
          placeholder="Select agent"
        />
        <DropdownSelect
          label="Assistant"
          value={assistantEmail}
          options={assistantOptions}
          onChange={setAssistantEmail}
          placeholder="Select assistant"
        />
        <button
          type="submit"
            disabled={membersControlsDisabled || !agentEmail || !assistantEmail}
          className="inline-flex h-10 items-center justify-center gap-2 rounded bg-[#0c66e4] px-4 text-sm font-bold text-white disabled:opacity-50"
        >
          <Plus className="h-4 w-4" /> Add
        </button>
      </form>
      {memberRows.map((member) => (
        <div
          key={`${member.agent_email}:${member.cs_email}`}
          className="grid grid-cols-[1fr_140px] items-center border-b border-[#ebecf0] px-4 py-2 last:border-b-0"
        >
          <div>
            <p className="text-sm font-bold">{labelForEmail(member.cs_email, candidateByEmail)}</p>
            <p className="text-xs font-semibold text-[#6b778c]">
              Assistant to {labelForEmail(member.agent_email, candidateByEmail)}
            </p>
          </div>
          <button
            type="button"
            disabled={membersControlsDisabled}
            onClick={() =>
              void run(async () => {
                await requestJson("/api/config/assistants", {
                  method: "DELETE",
                  body: JSON.stringify({
                    agent_email: member.agent_email,
                    cs_email: member.cs_email,
                  }),
                });
                await refreshMembers();
              }, "Assistant removed.")
            }
            className="inline-flex w-fit items-center gap-1 rounded px-2 py-1 text-sm font-bold text-[#bf2600] hover:bg-[#ffebe6]"
          >
            <Trash2 className="h-4 w-4" /> Remove
          </button>
        </div>
      ))}
      </section>
    </>
  );
}

async function requestJson(url: string, init: RequestInit = {}) {
  const response = await fetch(url, {
    ...init,
    headers: {
      "Content-Type": "application/json",
      ...(init.headers ?? {}),
    },
  });
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) {
    const error = new Error(payload.error ?? "Request failed.") as RequestJsonError;
    error.code = typeof payload.code === "string" ? payload.code : undefined;
    error.payload = payload;
    throw error;
  }
  return payload;
}

type RequestJsonError = Error & {
  code?: string;
  payload?: RequestJsonPayload;
};

type RequestJsonPayload = {
  [key: string]: unknown;
  archived_column?: {
    id?: unknown;
    label?: unknown;
    type?: unknown;
  };
};

function labelForEmail(
  email: string,
  peopleByEmail: ReadonlyMap<string, { name: string | null }>
): string {
  return peopleByEmail.get(email)?.name?.trim() || email;
}
